### ISSUE TITLE
All my executions have not ended, and no errors have been reported

### ISSUE THREAD

**Issue by jueji-shao** [frikky/Shuffle#100]
I added a The hello world node according to the document. After saving, click execute and there is no return value and no error message.

This is the status shown on the right

Status: EXECUTING
Started: 2020-07-09T09:09:06.000Z
Finished: 1970-01-01T00:00:00.000Z
Source: default

After that, it keeps this state, keeps turning around, there is no other output

-------------------- edit ----------------------
I saw some errors in the background as follows

![1594300286(1)](https://user-images.githubusercontent.com/34508654/87044209-cce10200-c228-11ea-8ade-143d591104dd.jpg)

I hope you can provide some suggestions

**Comment by jueji-shao** [comment]
I found the reason, the reason is that the directory name is not Shuffle
![1594349586(1)](https://user-images.githubusercontent.com/34508654/87111355-be7ffe00-c29b-11ea-9b22-9c35c353b614.jpg)


Forgive me for not being familiar with docker. Is the name related to the directory name inappropriate?

**Comment by frikky** [comment]
Hey jueji - glad you figured it out! 

I'm glad to tell you that this was fixed in a later build, but it's not ready for production yet, I'm afraid. You are right that it's related to the directory name. The "docker network" created by the docker-compose uses its parent to create the name.
