### ISSUE TITLE
GUI feature: resize workflow drawers

### ISSUE THREAD

**Issue by garanews** [frikky/Shuffle#101]
**Is your feature request related to a problem? Please describe.**
The condition section doesn't show all content if variables are long

**Describe the solution you'd like**
Have the possibility to resize the condition section

![image](https://user-images.githubusercontent.com/16938405/87043859-03e9f000-c1f6-11ea-87e9-c8ffdd58a3e6.png)

**Comment by frikky** [comment]
I'm not sure if this is the right way to approach the specific issue of conditions sizes (they should be re-made), but it sure as hell is a good feature to have in general - both on the left and right side.

**Comment by frikky** [comment]
Added a long time ago. Can drag from bottom right corner
