### ISSUE TITLE
Spontaneous crash on App Click

### ISSUE THREAD

**Issue by milesflo** [frikky/Shuffle#105]
**Describe the bug**
The UI crashes when I click on an app in a workflow to configure it

**To Reproduce**
1. Deploy local `build`-style docker-compose (uncomment `build`, comment `image`)
2. Set up default account through env variables
3. log into account
4. Create new workflow
5. Place an app on graph
6. Click on app
7. Observe crash

**Expected behavior**
The app should not crash when clicking on an app

**Screenshots**
![shuffle_crash](https://user-images.githubusercontent.com/14067660/87998111-d6316080-caab-11ea-839a-e227f1223aef.gif)

** Debug logs **
```
Uncaught TypeError: Er.authentication is undefined
    Nt Angular
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
    Angular 2
    a cytoscape.cjs.js:10553
    trigger cytoscape.cjs.js:10565
    Si cytoscape.cjs.js:10423
    trigger cytoscape.cjs.js:10523
    emit cytoscape.cjs.js:14206
    trigger cytoscape.cjs.js:10570
    Si cytoscape.cjs.js:10449
    trigger cytoscape.cjs.js:10523
    emit cytoscape.cjs.js:10692
    Ki cytoscape.cjs.js:11993
    load cytoscape.cjs.js:24990
AngularWorkflow.js:3079:3

```

**Comment by frikky** [comment]
Thanks! Looks like an uninitialized issue. I'll fix it tonight :+1:

**Comment by frikky** [comment]
I fixed the issue (it was something uninitialized) and a few other things. In general, you shouldn't run local builds, but rather use the docker images from Dockerhub (docker-compose pull) as I try to make these stable. The branch itself won't always be built from the same (even though I try). 

Your build process on the 1.0.0 branch should work again now though, but I'd suggest normal updates :)

**Comment by milesflo** [comment]
I disagree personally-- being able to deploy from Dockerfiles directly increases the transparency of the open source tool, rather than relying on exterior dependencies.

Great job on the microservice abstractions btw 👍

**Comment by frikky** [comment]
Didn't think about it in terms of transparency, and you're totally right. You should be able to know what code you're running :)

:fire:
