### ISSUE TITLE
Error with quick deploy

### ISSUE THREAD

**Issue by mouloren** [frikky/Shuffle#11]
When I am doing `docker-compose up` with the simple installation. 

```
shuffle-orborus | 2020/05/21 11:27:09 Failed making request: Get "http://shuffle-backend:5010/api/v1/workflows/queue": dial tcp 172.19.0.4:5010: connect: connection refused
shuffle-orborus | 2020/05/21 11:27:12 Failed making request: Get "http://shuffle-backend:5010/api/v1/workflows/queue": dial tcp 172.19.0.4:5010: connect: connection refused
shuffle-orborus | 2020/05/21 11:27:15 Failed making request: Get "http://shuffle-backend:5010/api/v1/workflows/queue": dial tcp 172.19.0.4:5010: connect: connection refused
shuffle-orborus | 2020/05/21 11:27:18 Failed making request: Get "http://shuffle-backend:5010/api/v1/workflows/queue": dial tcp 172.19.0.4:5010: connect: connection refused
```

**Comment by frikky** [comment]
Hey! I've run a quick fix, please pull and rebuild with the new docker-compose :)

```
git pull
docker-compose up -d --force-recreate
```

**Comment by nightdweller11** [comment]
still getting the same issue after update (also tried to delete and re-pull)

**Comment by nightdweller11** [comment]
there's also this error in the orborus log 

2020/05/21 13:37:04 Failed making request: Get "http://shuffle-backend:5010/api/v1/workflows/queue": dial tcp 172.18.0.4:5010: connect: connection refused

2020/05/21 13:37:07 Failed making request: Get "http://shuffle-backend:5010/api/v1/workflows/queue": dial tcp 172.18.0.4:5010: connect: connection refused

**Comment by frikky** [comment]
This was a bug with the .env file in the root directory. I made a change (pull again), but if you want to get it to run properly, change the "OUTER_HOSTNAME" variable in .env to your IP or hostname. 

I'm trying to find a way to do this programatically without a deployment script (maybe I need one), but env files aren't necessarily the best for that

**Comment by mouloren** [comment]
and now...
```
shuffle-frontend | 10.0.1.213 - - [21/May/2020:14:44:50 +0000] "GET /adminsetup HTTP/1.1" 304 "
```

**Comment by frikky** [comment]
Seems to be an issue with the frontend docker image, which was just fixed. From the root directory, run:

```
docker-compose down
docker-compose pull
docker-compose up -d
```

**Comment by mouloren** [comment]
Awesome!! 
Thank you!!

**Comment by nightdweller11** [comment]
works! thanks!

**Comment by liuyien** [comment]
I am facing the same issue. Regardless of whether I set http_proxy and https_proxy in the .env file or not, the same error occurs.

2024/11/19 11:42:37 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused
2024/11/19 11:42:39 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused
2024/11/19 11:42:41 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused
2024/11/19 11:42:43 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused
2024/11/19 11:42:45 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused
2024/11/19 11:42:47 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused
2024/11/19 11:42:49 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused
2024/11/19 11:42:51 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused
2024/11/19 11:42:53 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused
2024/11/19 11:42:55 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused
2024/11/19 11:42:57 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused
2024/11/19 11:42:59 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused
2024/11/19 11:43:01 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused

**Comment by frikky** [comment]
> I am facing the same issue. Regardless of whether I set http_proxy and https_proxy in the .env file or not, the same error occurs.
> 
> 2024/11/19 11:42:37 [WARNING] Failed making request to http://shuffle-backend:5001/api/v1/workflows/queue: Post "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.22.0.3:5001: connect: connection refused 2024/11/19 

Heyo,

can you try using the external IP as in `http://<externalip>:5001` for the BASE_URL?

PS: Don't set it anything the .env file, as it is read differently for different docker version - set it directly for the "Orborus" container in the docker-compose.yml file directly. This includes HTTP_PROXY.
