### ISSUE TITLE
Can't see start/stop webhook

### ISSUE THREAD

**Issue by prashantvidja** [frikky/Shuffle#118]
**Describe the bug**
I was testing webhook trigger and it was working well but after some time I got the false message in the response of `curl -XPOST WEBHOOK_URL`.

**To Reproduce**
No idea what happened immediately, just add one webhook and one test node in the workflow. then trigger workflow using curl with webhook URL.

**Expected behavior**
It should execute workflow instead of I am getting the false message in the response of the CURL.

**Screenshots**
1. webhook URL execution using curl
![image](https://user-images.githubusercontent.com/26060662/90627404-81fbd680-e239-11ea-811f-2a65c65082ad.png)

2. getting error in backend while execution
![image](https://user-images.githubusercontent.com/26060662/90627629-d010da00-e239-11ea-90e0-a56ace91ea71.png)

** Debug logs **

> 2020/08/19 10:52:22 Session 6e259d24-1987-4429-8c66-9280b45218f3 doesn't exist (api auth): datastore: no such entity
> 2020/08/19 10:52:22 Api authentication failed in getworkflows: datastore: no such entity
> 2020/08/19 10:52:40 Saved new workflow a031d929-d99a-4fd3-b839-9197da53c295 with name test
> 2020/08/19 10:52:40 APPENDING NEW APP FOR NEW WORKFLOW
> 2020/08/19 10:52:43 http: superfluous response.WriteHeader call from main.getWorkflowExecutions (walkoff.go:4898)
> 2020/08/19 10:53:04 GetWorkflow start
> 2020/08/19 10:53:04 GetWorkflow end
> 2020/08/19 10:53:04 Trigger WEBHOOK: uninitialized
> 2020/08/19 10:53:04 Apps set starting
> 2020/08/19 10:53:04 Saved new version of workflow test (a031d929-d99a-4fd3-b839-9197da53c295)
> 2020/08/19 10:53:44 Failed getting hook: datastore: no such entity
> 2020/08/19 10:54:22 http: superfluous response.WriteHeader call from main.getWorkflowExecutions (walkoff.go:4898)
> 2020/08/19 10:55:17 **Failed getting hook: datastore: no such entity**
> 2020/08/19 11:01:27 **Failed getting hook: datastore: no such entity**

PS: Highlighted error getting during the webhook URL fire.

Thanks

**Comment by frikky** [comment]
Hey there! Did you click "start" on the webhook node? 

I may have to make this automatically start or add better logging for it :+1:

**Comment by prashantvidja** [comment]
Not understand, There is not any "start" to click.
Could you please explain?

**Comment by prashantvidja** [comment]
I think the issue is this
![image](https://user-images.githubusercontent.com/26060662/90674872-60214480-e277-11ea-8033-ed49279e1927.png)
How can I make it running?

**Comment by prashantvidja** [comment]
Sorry, I find the start button. somehow in my browser start button is not showing. after did zoom out then I show it.
Thanks u.

**Comment by frikky** [comment]
ooh, that's a bad user experience anyway - .

**Comment by prashantvidja** [comment]
1536x864

I have an ubuntu machine so actual resolution 1920X1080 but in this resolution, the font becomes very small so I have scaled it to 1536x864 using below ubuntu feature.
![image](https://user-images.githubusercontent.com/26060662/90725129-4fa3b500-e2dd-11ea-831a-2fa763a0bb61.png)

**Comment by frikky** [comment]
Thanks! :+1:

**Comment by frikky** [comment]
Hey there! I did the following quickfix:
* Set webhooks to autostart to remove confusion
* Added a proper outline to understand that there are buttons there
* Removed the execution field to make it easier to see the full thing

Thanks for the report :)

![image](https://user-images.githubusercontent.com/5719530/91019919-0eb7e300-e5f2-11ea-9172-05c4e5648d91.png)

**Comment by frikky** [comment]
Pushed to master and dockerhub. Make sure to [update](https://shuffler.io/docs/configuration#updating_shuffle) :)
