### ISSUE TITLE
Can't see "data from previous action" option at condition configuration

### ISSUE THREAD

**Issue by prashantvidja** [frikky/Shuffle#119]
**Describe the bug**
Can't see "data from previous action" option at condition configuration only showing static option. 

**To Reproduce**
1. Create workflow.
2. connect any two apps.
3. Click on flow and try to set the condition

**Expected behavior**
there should show the same option as below.
![image](https://user-images.githubusercontent.com/26060662/90806390-91af1400-e33a-11ea-94ab-71af01587e62.png)

**Screenshots**
it showing only static
![image](https://user-images.githubusercontent.com/26060662/90806170-44cb3d80-e33a-11ea-903e-48531b83b5d4.png)

Thanks

**Comment by frikky** [comment]
You're right! I mean to remove it in the future, but was probably a bit too fast.

The reason: The static field should have a good autocomplete system, making it possible for you to do everything without them.

I'll re-add them until it gets to that stage :+1:

**Comment by frikky** [comment]
Hey again!

I ended up adding the autocomplete system, since it will be way more comprehensive when it's up and running properly. It's not extensive right now, but has access to the functionality of the "Previous action", variables and basic JSON autocompletion.

Here's what the menu looks like when you click it in a condition :+1: 
![image](https://user-images.githubusercontent.com/5719530/91014796-4fabf980-e5ea-11ea-804e-0afeb46cd8a1.png)

**Comment by prashantvidja** [comment]
Thanks for the quick fix,
How I update? just need to pull the new docker images as per the guide.
And also before raising this issue I tried to fix this on my own but somehow not able to log in and getting below error. I have installed all things using your local development guide. 
![image](https://user-images.githubusercontent.com/26060662/91039140-9bca5e80-e629-11ea-910a-7f1b974844ec.png)

Thanks again

**Comment by frikky** [comment]
Sorry - haven't pushed the changes to dockerhub yet. I'll get it done tonight :)

I should probably check the local dev guide again and clean it up. There are three parts:
1. Frontend
2. Backend
3. Database

Looks like either of these issues: 
backend can't connect to database
frontend can't connect to backend
frontend isn't running on localhost:3000

**Comment by frikky** [comment]
Pushed to master and dockerhub. Make sure to [update](https://shuffler.io/docs/configuration#updating_shuffle) :)

**Comment by prashantvidja** [comment]
Hey @frikky 

I have tried to update the shuffle docker image using your guide.
for the first two pull command, it did not pull any new image. showing up to date.
so after that, I have done all the pending steps. and checked but it is not showing this update.
Could you please check it out once?

Thanks
