### ISSUE TITLE
UI App Creator Url Path bug

### ISSUE THREAD

**Issue by urechi** [frikky/Shuffle#120]
Hi,

My rest endpoint is like https://hostname.domain.com/service/1.0/rest/accounts?email=someemail@domain.com
App Creator -> CREATE FROM SCRATCH
Base URL: https://hostname.domain.com
Under Actions I've got:
Url Path: /service/1.0/rest/accounts?email={someemail}

I've first noticed that In the workflow the dot (.) is being removed so the called URL become something like:
https://hostname.domain.com/service/10/rest/accounts?email={someemail}

Then I've changed the Base URL to "https://hostname.domain.com/service/1.0/rest" as a workaround which seems to solve the issue with the dot.
The URL Path within the Action is now "/accounts?email={someemail}"
Let's say the variable value is someemail@domain.com, playing the workflow will result in a GET call such as:
https://hostname.domain.com/service/1.0/rest/accounts?email=someemail@domain.com?someemail=someemail@domain.com

Is this a bug or am I doing something wrong here?

Thanks,
Adrian

**Comment by frikky** [comment]
The last one was an issue with query parsing, where it was both a part of the URL and as a query itself. 

Nice finds, keep them coming :fire:

**Comment by frikky** [comment]
Pushed to master and dockerhub. Make sure to [update](https://shuffler.io/docs/configuration#updating_shuffle) :)
