### ISSUE TITLE
A communication platform for Shuffle users

### ISSUE THREAD

**Issue by urechi** [frikky/Shuffle#121]
Hey,

May I recommend a communication platform for Shuffle users where we can chat? Maybe [Slack](https://slack.com/intl/en-gb/pricing/free)? If you create a workspace you can then invite people.

Thanks,
Adrian

**Comment by frikky** [comment]
Hey again! We ended up creating a discord server here: https://discord.gg/9UA5ug

Come over and hang out. We'll make it more of a community over time :+1:
