### ISSUE TITLE
Consider the possibility of using Kubernetes

### ISSUE THREAD

**Issue by aoighost** [frikky/Shuffle#13]
Docker compose is good for portability, however with Kubernetes able to run on windows through docker desktop, adding kubernetes support and creating helm charts would help enable more flexibility in cloud deployment, as well as open new doors like the ability to use prometheus for monitoring.

**Comment by frikky** [comment]
I'm way more proficient at using Docker directly than the distribution services like Kubernetes or Swarm. This is a part of a future roadmap for sure. 

I'd love to learn more about what you're thinking if you're available for a chat some day (mail me at frikky@shuffler.io)

**Comment by aoighost** [comment]
Check your email

**Comment by frikky** [comment]
As far as I'm concerned, this was fixed in #110 :100: 

Doing cleanup of issues.
