### ISSUE TITLE
Document process to create and install custom apps

### ISSUE THREAD

**Issue by peter-clemenko** [frikky/Shuffle#14]
It would be really helpful to document where and how to install custom apps based on the walkoff spec.

**Comment by frikky** [comment]
Working to rewrite the super old documentation that currently exists: https://github.com/Shaffuru/shuffle-docs

Do you by chance have a lot of custom apps?

**Comment by aoighost** [comment]
Sadly not as many as I'd like. That being said, I have a feeling I'm going  to drop a lot of red team apps when this is done.

**Comment by frikky** [comment]
Excited to see what you have in store. I'll add an upload button for custom apps as I dont have a good way of loading locally right now (just from github)

**Comment by aoighost** [comment]
Being able to add from a custom git repo (preferably including a private one) would be a very nice feature to have

**Comment by frikky** [comment]
Added the possibility for private (and public) github repos in 33e8d089b0bfbcd24f4ce846796c1c5d78d2b5b9. It will be a part of the next frontend & backend update :)

**Comment by frikky** [comment]
I haven't documented the creation itself properly yet, but I did add how to install / upload custom apps. I'm working on the new build for it right now

https://shuffler.io/docs/apps#upload_custom_app
