### ISSUE TITLE
Add Elasticsearch Database Query support

### ISSUE THREAD

**Issue by ion-storm** [frikky/Shuffle#144]
Adding Elasticsearch as a queryable database could open a ton of options for Shuffle.  Shuffle could theoretically act and respond to endpoint eventlogs with sysmon & Mitre ATT&CK with winlogbeat for an example.  
Allowing Shuffle to query and get table data from elasticsearch would open an endless realm of automation possibilities.

**Comment by frikky** [comment]
Hey! This was added to the OpenAPI spec and seemed to work! I purposefully didn't add multi/bulk updates yet

https://github.com/frikky/security-openapis
