### ISSUE TITLE
Unable to get to Jsonpath in nested json?

### ISSUE THREAD

**Issue by ion-storm** [frikky/Shuffle#149]
How do I get Shuffle to show only the Alert for each message in this json from Graylog? Jsonpath doesnt seem to work with $..message.Alert
` [{"highlight_ranges": {}, "message": {"Alert": "Account Manipulation", "_id": "d097c6f2-f6b6-11ea-aaa1-0050569f425d", "timestamp": "2020-09-14T18:19:24.427Z"}, "index": "test", "decoration_stats": null}, {"highlight_ranges": {}, "message": {"Alert": "Account Manipulation", "_id": "d099c2c3-f6b6-11ea-aaa1-0050569f425d", "timestamp": "2020-09-14T18:19:24.427Z"}, "index": "test", "decoration_stats": null}, {"highlight_ranges": {}, "message": {"Alert": "Account Manipulation", "_id": "d097c6f2-f6b6-11ea-aaa1-0050569f425d", "timestamp": "2020-09-14T18:19:24.427Z"}, "index": "mitre_0", "decoration_stats": null}, {"highlight_ranges": {}, "message": {"Alert": "Account Manipulation", "_id": "d099c2c3-f6b6-11ea-aaa1-0050569f425d", "timestamp": "2020-09-14T18:19:24.427Z"}, "index": "mitre_0", "decoration_stats": null}, {"highlight_ranges": {}, "message": {"Alert": "Notepad connecting to the internet", "_id": "c789d084-f6b6-11ea-aaa1-0050569f425d", "timestamp": "2020-09-14T18:19:09.444Z"}, "index": "1_207", "decoration_stats": null}, {"highlight_ranges": {}, "message": {"Alert": "Notepad connecting to the internet", "_id": "c789d084-f6b6-11ea-aaa1-0050569f425d", "timestamp": "2020-09-14T18:19:09.444Z"}, "index": "mitre_0", "decoration_stats": null}, {"highlight_ranges": {}, "message": {"Alert": "Obfuscating Hacking Commands", "_id": "ae8ad8f5-f6b5-11ea-aaa1-0050569f425d", "timestamp": "2020-09-14T18:11:17.202Z"}, "index": "mitre_0", "decoration_stats": null}, {"highlight_ranges": {}, "message": {"Alert": "Account Manipulation", "_id": "0f9d3001-f6b3-11ea-aaa1-0050569f425d", "timestamp": "2020-09-14T17:52:31.810Z"}, "index": "test_201", "decoration_stats": null}, {"highlight_ranges": {}, "message": {"Alert": "Account Manipulation", "_id": "0f9d3000-f6b3-11ea-aaa1-0050569f425d", "timestamp": "2020-09-14T17:52:31.810Z"}, "index": "test_201", "decoration_stats": null}, {"highlight_ranges": {}, "message": {"Alert": "Account Manipulation", "_id": "0f9d3001-f6b3-11ea-aaa1-0050569f425d", "timestamp": "2020-09-14T17:52:31.810Z"}, "index": "mitre_0", "decoration_stats": null}, {"highlight_ranges": {}, "message": {"Alert": "Account Manipulation", "_id": "0f9d3000-f6b3-11ea-aaa1-0050569f425d", "timestamp": "2020-09-14T17:52:31.810Z"}, "index": "mitre_0", "decoration_stats": null}]`

**Comment by frikky** [comment]
Confirmed proper stupid JSON parsing bug!

Here's my query (which should work): $Start_node.#.message.alert

I'll get it done asap.

**Comment by frikky** [comment]
This got us to properly fix JSON items and nested loops. Update the App SDK, then your apps!

```
docker pull frikky/shuffle:app_sdk
```
