### ISSUE TITLE
Workflow page won't load

### ISSUE THREAD

**Issue by FatnLazy** [frikky/Shuffle#152]
Hi after createing a work flow i shut down the system in order to update it with docker-compose pull after powering it on again for some reason the workflows page wont load its just a blank white page and nothing happens i can go to the apps page if i change the url from https://localhost:3443/workflows to https://localhost:3443/apps 

steps to reproduce :

1) new installetion of suffle 
2) creating a user 
3) creating a workflow
3) shutting down the system with docker-compose down
4) running the following commands
* git pull
*docker-compose pull
*docekr-compose up 
5) trying yo access the workflows page again.

PS: all the commands were ran from the shuffle folder

**Comment by frikky** [comment]
Well shit, that's a frontend bug. To help us debug this, please:
1. Open a new tab
2. Right click and hit "inspect" (or similar)
3. Go to "Console" in the debug menu
4. Open https://localhost:3443/workflows
5. Please send any errors your see. They should be glaring red. These will help us a lot.

If you don't have any valuable information in the database, please delete the folder ./shuffle-database
If you DO need the data, I'll need you to help me help you debug it (see above) OR send us the ./shuffle-database folder.

Thanks a lot and sorry for the issue

**Comment by frikky** [comment]
Got an update from @garanews:

```
01 PM] garanews: TypeError: Cannot read property 'length' of null
    at Ct (Workflows.jsx:546)
    at Ja (react-dom.production.min.js:153)
    at Rs (react-dom.production.min.js:257)
    at nl (react-dom.production.min.js:228)
    at el (react-dom.production.min.js:227)
    at Hs (react-dom.production.min.js:220)
    at react-dom.production.min.js:120
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Li (react-dom.production.min.js:119)
    at Wi (react-dom.production.min.js:120)
Ko @ react-dom.production.min.js:193
```

This put me on the right track :+1:

**Comment by frikky** [comment]
You can now update! 

https://shuffler.io/docs/configuration#updating_shuffle
