### ISSUE TITLE
Check if any Docker image is outdated

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#161]
Since the backend has access to the Docker daemon, periodically check if the images are out of date and promote auto-updates.

**Comment by anusha5695** [comment]
Hi @frikky , could you elaborate more? Do you want to pick the latest image for backend everytime the app is run?

**Comment by frikky** [comment]
Hey @anusha5695 - I'm not sure what the best way is, but I'm thinking it should verify with the cloud version in the future, but for now it should verify with https://github.com/frikky/shuffle-apps and their versions.

What you're talking about/want is probably more like #135

**Comment by frikky** [comment]
Kind of same as #212. Will continue it there.
