### ISSUE TITLE
Create delete button for python apps

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#165]
It's currently only active for OpenAPI apps. Can also be done for python. Refresh will make it re-show.

**Comment by prashantvidja** [comment]
@frikky 
Anyhow, can I delete python apps?
because I have created too many apps now all things are messed up.

**Comment by frikky** [comment]
Hey! 

Until you get the button, you can use the API. I added a reference to it to the API just now. 

https://shuffler.io/docs/API#delete_an_app

So doing it with Shuffle (app will come soonish):
1. Get your API key
2. Get all apps with the HTTP app (DELETE & header = {"Authorization": "Bearer $apikey"})
3. Delete all apps with the HTTP app

**Comment by prashantvidja** [comment]
Hey @frikky 
I have tried to delete the app with API but did not work.
![image](https://user-images.githubusercontent.com/26060662/95819394-86c59e00-0d43-11eb-8013-5db3331e9c3d.png)

Did not get any error or any response.
Also, I have added one app using the "Create from scratch" feature. that has a delete button. but when I try to delete that it did not work. When I checked API in the browser network console I got a response `{"success": true}`.

But, when I reload the /apps page deleted app already there.

Thanks

**Comment by frikky** [comment]
Added bug to the issue, as that in theory should work 😅

I'll take a closer look later on.

**Comment by frikky** [comment]
Hey @prashantvidja - have you updated and tried to delete?

**Comment by prashantvidja** [comment]
yes, just tested.
It is working fine.
Thanks
