### ISSUE TITLE
Docker container deleted without finish.

### ISSUE THREAD

**Issue by prashantvidja** [frikky/Shuffle#167]
**Describe the bug**
In one of the nodes, I have put time.sleep(60) for the sleep process for 60 seconds before the next validation check.
So my last node takes almost 6 to 7 min and when I see `docker ps -a`  all containers are deleted.
when I see the workflow in GUI. 
![image](https://user-images.githubusercontent.com/26060662/94855538-4cf3be00-044c-11eb-9855-b17b6b14eff6.png)
it is not showing any error or any result.

**To Reproduce**
1. Make one app for sleep the execution for a minimum 6 min.
2. Create a workflow using that sleep app
3. execute workflow
4. Check does it successfully finish or not?
...

**Expected behavior**
The container should run as long as the execution running.

**Comment by frikky** [comment]
Heyo and thanks!

Looks like you've indeed ran into the cleanup process (ever 5 minutes) which usually helps a lot. 
Anyway, this should definitely not happen if the container is actually working.

I'll up it to 600 by default and make it possible to configure it to your liking :+1: 

Would that solve the issue?

**Comment by prashantvidja** [comment]
Thanks, @frikky for the quick replay.

I think it will not help because sometimes my container runs even higher. basically, In the flow, I require one manual validation which sometimes takes more than 5 hrs as well. So In the container, I am executing the validation check API every 5 min. Once validation is done by any person then it will finish.
Can we do delete only the finished containers?

Thanks

**Comment by frikky** [comment]
I see - I got a feature for that in the cloud version btw: see the trigger "User input". It's meant to continue a workflow based on user input. What's your current implementation?

I'll make what you said an exception you can add, but it may take a bit longer. Problem with it is that some containers are currently doomed to never stop (e.g. during development), which may never ever removed.

**Comment by prashantvidja** [comment]
yes, I have seen the "User input" feature in the cloud version. But it will not work in my case I needed to make validation inside the container.
As I have seen you have added a timeout variable in docker-compose.yaml. it would be great if you do that.
I can increase the time.

Thanks

**Comment by frikky** [comment]
It's done - do this: 
```
docker-compose down
docker pull frikky/shuffle:orborus
# EDIT docker-compose.yml according to the image below: set the time to be super high
docker-compose up -d
```

**Comment by prashantvidja** [comment]
Thank you very much let me check that.

**Comment by prashantvidja** [comment]
it works. Thanks a lot.

**Comment by frikky** [comment]
Yay! You may want to think about running multiple Orborus containers (multiple environments) on different servers to prevent memory and storage issues long term.
