### ISSUE TITLE
Add authentication features like Oauth2

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#168]
Add an edit button to authentication. Make this a destructive action, which DOESNT show the last data since it can't be retrieved from the backend anyway.

![image](https://user-images.githubusercontent.com/5719530/95062483-4f307380-06fd-11eb-8be7-454ff760a058.png)

**Comment by frikky** [comment]
- [ ] Edit existing authentication
- [ ] Add button for "apply to all nodes". Should literally go through all workflows and apply the authentication to all existing nodes
- [ ] Add a way to add authentication in this view. No need to add nodes first.

**Comment by arnydo** [comment]
Interested in ability to utilize Oauth2 as well.

**Comment by frikky** [comment]
> Interested in ability to utilize Oauth2 as well.

Added prototype implementation of Oauth2. This one will probably take a while to get stable, but it's already _pretty_ dynamic. Examples will come in the coming weeks!

**Comment by frikky** [comment]
Getting very close now :eyes: 

Just need some documentation and testing

**Comment by frikky** [comment]
Even more lists related to Oauth2:

## App Creator
- What should be copied into the Oauth2 fields?
- Add better names in app creator
- Remove everything after ? in the URLs
- Remove "Header" by default in Token URL
- Make SCOPE field required / highlighted in Orange
- Add link to HOW TO USE Oauth2 (and other Auth) doc
- Make "New action" highlighted if 0 actions
- Enforce Base URL if Oauth2 is defined?
- Submit button for actions should be highlighted, not outlined?
- How to deal with no Base URL, but action with URL? 
- - ... =undefined added to headers when autocompleting from o

## Workflow UI
- Oauth2 not enforcing authentication first (?)
- Have something that says to find "scope", and put it UNDER the Secret and ID
- Add info for https://shuffler.io/set_authentication to UI for defining apps
- Oauth2 missing "Extra authentication" fields in auth on left side
- Scope field should be required for Oauth2 in workflow authentication. Field should also have a name. 
- No authentication selected by default for Oauth2 app?

- Add need to save after auth is added (?)
- Can we run it for multiple orgs without a new Oauth2? Save Client ID and secret somewhere secret.

**Comment by frikky** [comment]
Fixed MOST of the above. Autoselection is not ready yet, and proper documentation is lacking.

**Comment by frikky** [comment]
This all works well and is in use by plenty of apps, including the refresh token handling! :)
