### ISSUE TITLE
Workflow execution issue - webhooks

### ISSUE THREAD

**Issue by rams3sh** [frikky/Shuffle#17]
```
shuffle_app_sdk_1 exited with code 0
worker_1    | 2020/05/22 15:53:49 Setting up worker environment
worker_1    | 2020/05/22 15:53:49 No AUTHORIZATION key set in env
worker_1    | panic: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
worker_1    | 
worker_1    | goroutine 1 [running]:
worker_1    | main.shutdown(0x0, 0x0, 0x0, 0x0)
worker_1    | 	/home/frikky/git/shuffle/functions/onprem/worker/worker.go:229 +0x69e
worker_1    | main.main()
worker_1    | 	/home/frikky/git/shuffle/functions/onprem/worker/worker.go:788 +0xc99
shuffle_worker_1 exited with code 2
```
I have been getting this error. Also I guess it has something to do with reason on why my test workflow is also not working.

Can you let me know whats the issue going on here ?

**Comment by frikky** [comment]
Hola!

This is actually working as expected during docker-compose setup, but is redundant. I removed them in the latest commit 6fe0267140c32d9cc81c186ed8f1633b00e2b659.

What is the issue with your workflows? Are they stuck on EXECUTING or something similar?

**Comment by rams3sh** [comment]
Ohh.. I think either my understanding is wrong or the workflow is not working as expeted

This is the workflow I created.
![image](https://user-images.githubusercontent.com/5143597/82693777-be8e5500-9c7f-11ea-8404-855d61e67639.png)

I had executed the workflow, and workflow gives out result saying it was executed sucessfully.
I dont know if that is what is the function of the above workflow.

Based on my inference or my intention, I wanted to have a webhook , which when hit with GET Request triggers the Hello World from the test app.

Am I doing it right based on my requirement, or is my understanding wrong ?

So what does the above workflow do ?

I can raise a separate issue and close this issue here , if this has nothing to do with the title.

Also , I would request to have easy to understand beginner docs to start experimenting with shuffle and its basic architecture.

**Comment by frikky** [comment]
The culprit seems to be my code, and not your understanding :)

I didn't even think about webhooks as GET requests - they only accept POST requests right now, as webhooks usually contain some information. Try a POST request and it should work!

The beginner/getting started docs will be the next blogpost, going through the creation of a workflow that runs a webhook and/or trigger with some cool data.

**Comment by rams3sh** [comment]
Sure thanks mate.

So thats what I was expecting, however , even if its a POST request , why does the workflow executes and gets completed even before I hit a request to it. I expect it to keep running throughout and keep displaying the output "Hello World" somewhere as and when I keep sending the POST request until I stop the execution.

**Comment by rams3sh** [comment]
Anyways I will wait for the blogpost to start off my experimentation and get a good grip off it. :) :)

**Comment by frikky** [comment]
Not sure if I catch your drift exactly. Would you want to see every execution pop up on screen? E.g. if a webhook runs, would you like to see that? 

Right now, executions can only be seen under /workflows. I'll add this as a feature with realtime updates for 1.0 release :)

**Comment by rams3sh** [comment]
My bad man. Sure its working as expected. I was imagining a visual where the play (execute) button is the one which should be clicked for activating the workflow to kick in into affect and it has to be continuously in mode of running for workflow to be active. But in reality, the workflow kickstarts already as soon as I connect the Web Hook Action to the test app.

The execute button was misleading me visually to think that the workflow ran and its executed succesfully once I clicked it leaving me confused to what happened as I havent even triggered a webhook; when in fact it meant that it is just to test it once and not an activate button for the workflow.

Anyways , thanks for your patience for helping out.

**Comment by frikky** [comment]
No worries, it probably means bad UX on my part as well. I'll try to remember to document this properly and maybe change the frontend.

Glad you like it! For more questions, I just created a gitter chatroom: https://gitter.im/Shuffle-SOAR/community#
