### ISSUE TITLE
Multi for-loop issue

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#170]
RE #163 - there's and issue with MULTI for-loop. Example:
Node 1 (test_1): ["hello1", "hello2", "hello3"]
Node 2 (test_2): ["hello4", "hello5", "hello6"]
Node 3 (test_2): ["hello7", "hello8", "hello9"]

This should turn into 27 UNIQUE for-loops. Right now, that's not happening and the App SDK location for fixing this is weird.

Issue 2 - loops within strings:
hey $Start_node.testlist.#

SHOULD run the loop within the item. Instead, it sends the whole thing in every part of the loop. 

Edit: Since they're the same length, it should NOT be 27 unique loops, but triplets (hello1, hello4, hello7). This could be a configuration item later on.

**Comment by dadokkio** [comment]
It would be nice to understand if I have 2 parallel blocks with loop that go in a single block what happens.
My idea is that the final block will be execute for each pair o elements of the list.

**Comment by frikky** [comment]
@dadokkio: Yep, that's what I'm thinking of with rule 1. The hard question however, is what happens if they're not the same structure / size? E.g. say you have the simple loops:

["ip", "ip"]
["1.1.1.1", "1.2.3.4"]

This should turn into pairs as you said. But what if it's this?
["ip", "ip"]
["1.2.3.4", "4.5.6.7", "1.1.1.1"] 

What do we do? This is why the multiplier exists. It turns it into a 2d array of 2x3.

**Comment by dadokkio** [comment]
I could have also more interesting example :angel: .. if the first is a nested list and the second is not for example 
Mi idea is that it'll pick each list from the first and the single element from the second one.

**Comment by frikky** [comment]
Ye, that's where the "structure" comes in. There has to be some rules to follow, otherwise I'll get lost while fixing this :P

**Comment by frikky** [comment]
Missing: 
1. Structure control. If you use # in the end or not doesn't matter right now, as it just recurses if it sees a loop. Need to regain control of basic and inner loops.

**Comment by frikky** [comment]
Fixed another issue with loop control by adding check for if the user uses # or not. This is really easily testable with the "Filter List" app.
![image](https://user-images.githubusercontent.com/5719530/102233317-702cf600-3ef0-11eb-9f48-87ca202f7865.png)

**Comment by frikky** [comment]
"New" issue: Multiple for-loops in a single field compared to multiple fields. Example:

```$data = [{"name": "leandro", "color": "red"}, {"name": "felipe", "color": "blue"}]```

Wanted result:
leandro - red
felipe - blue

What makes sense:
```$data.#.name - $data.#.color```

This throws and error right now.

**Comment by frikky** [comment]
This is solved if Shuffle is used with Subflows. We generally tend to not want users to have double loops at all for now. May change in the future.
