### ISSUE TITLE
Large result value issue

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#171]
2020/10/09 04:59:01 Error adding workflow_execution: rpc error: code = InvalidArgument desc = Property results is too long. It cannot exceed 1048487 bytes.

If the result exceeds that limit, there is no return. Not sure how to handle this one, but it's certainly a bug that needs fixing.

**Comment by frikky** [comment]
As we're running datastore, large values can't be handled properly yet. This means we had to make a workaround. Here's more info: https://cloud.google.com/datastore/docs/concepts/limits

Set arbitrary result limit to 0.5MB for now.

**Comment by peter-clemenko** [comment]
Ping me when this is fixed properly

**Comment by arnydo** [comment]
Is this an issue on prem as well? Receiving this error today.

**Comment by frikky** [comment]
> Is this an issue on prem as well? Receiving this error today.

Yep. It's a database limit, and has only occurred when you get really large results so far. It'll be fixed as we swap databases at some point. I was thinking about fixing it by saving to files and such, but that would be stupid D:

**Comment by arnydo** [comment]
Bummer. Trying to convert the body of an email to base64 and getting this error.

**Comment by frikky** [comment]
> Bummer. Trying to convert the body of an email to base64 and getting this error.

:( any workaround potential? That's gotta be a REALLY big email

**Comment by arnydo** [comment]
Ill figure something out. It really wasn't a big email though...less than 1MB
