### ISSUE TITLE
Import OpenAPI as file

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#178]
There should be an easy upload option. Drag and drop or similar.

**Comment by setheal** [comment]
Hey @frikky can you give me more details please ?

**Comment by frikky** [comment]
Hey @setheal, sure! What I'm thinking is the ability to import a file and/OR drag and drop a file into the "Apps" screen, which will then be loaded and sent to the backend to become a new OpenAPI spec. All that should require change is the frontend. File upload examples can be found in the [app editor](https://github.com/frikky/Shuffle/blob/a700846df6977c89da74e75aec4ea508ea3bd28d/frontend/src/views/AppCreator.jsx#L1729).

Import file (clicking): I would probably remove the "paste JSON/YAML" and rather put an "upload" button there for files. [Here's the code location ](https://github.com/frikky/Shuffle/blob/a700846df6977c89da74e75aec4ea508ea3bd28d/frontend/src/views/Apps.jsx#L1379)
![image](https://user-images.githubusercontent.com/5719530/96817135-f9f3a200-141e-11eb-9adc-352797fca91e.png)

Drag and drop (anywhere in this screen):
![image](https://user-images.githubusercontent.com/5719530/96817067-d16ba800-141e-11eb-85fe-1d3ae1c16eb0.png)

The upload should do the same for both these options. Start with the first one, as drag and drop always is a pain :+1:

**Comment by frikky** [comment]
Tell me if you need to know more. This is 100% frontend work :fire:

**Comment by setheal** [comment]
Ok, if I understand correctly. In the first screen I replace the "paste JSON/YAML" part with a button to upload a JSON or YAML file. And in the second screen add the ability to drag&drop directly the file. Am I right ?

**Comment by frikky** [comment]
Yep. Essentially, the whole point is that you should be able to drop an OpenAPI spec / full app anywhere here, and let it be usable within only a few seconds.

Please tell me how I can help, and good luck! :100:

**Comment by setheal** [comment]
Ok, you can assign it to me. I'll do the PR asap :)
