### ISSUE TITLE
add github tag: security orchestrator

### ISSUE THREAD

**Issue by falcorocks** [frikky/Shuffle#192]
Hi,
I think adding the words "security orchestrator" to your github tags/readme would increase significantly your visibility.
* right now, googling "open source security orchestrator" does not lead to this project!
* shuffle is the _only_ open source security orchestrator available that is _actually_ an orchestrator.

**Comment by frikky** [comment]
Not a bad idea, thanks! 

I've quickly added it to the tags just now. For reference, what DID you find when you googled it? The first result for me (after ads), followed by Patrowl.

**Comment by falcorocks** [comment]
Nice, happy to help with this good project :)
After the ads I get Crowdstrike Falcon Orchestrator, Patrowl, a few "top N orchestration projects" and "brucon". I now see your medium article towards the end of the first page. It is possible that I missed it on my first google search!
Adding the tags here will hopefully bring more attention anyways :)

**Comment by frikky** [comment]
Thanks! 

It will probably help if I do some SEO work on the website as well :+1:
Server Side rendering is pain.
