### ISSUE TITLE
Not able to build worker image.

### ISSUE THREAD

**Issue by prashantvidja** [frikky/Shuffle#199]
**Describe the bug**
I have made some changes to the worker as per my requirement. then not able to build a worker.
even I reverted back changes I am not able to build.

**To Reproduce**
```
root@ip-172-31-2-181:~/Shuffle/functions/onprem/worker# docker build . -t frikky/shuffle:worker
Sending build context to Docker daemon  51.71kB
Step 1/14 : from golang as builder
 ---> 4a581cd6feb1
Step 2/14 : WORKDIR /app
 ---> Using cache
 ---> c5e6fa689113
Step 3/14 : RUN go get -u github.com/docker/docker/api/types
 ---> Using cache
 ---> 43d98d2cdfba
Step 4/14 : RUN go get -u github.com/docker/docker/api/types/container
 ---> Using cache
 ---> 2772b12febe3
Step 5/14 : RUN go get -u github.com/docker/docker/client
 ---> Using cache
 ---> 17ef6fa2dd0f
Step 6/14 : COPY worker.go /app/worker.go
 ---> Using cache
 ---> 0594a33bf7d4
Step 7/14 : RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o worker .
 ---> Running in 23e2c1a41563
# _/app
./worker.go:705:7: undefined: exit
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o worker .' returned a non-zero code: 2
```

**Comment by frikky** [comment]
Looks like an issue on line 705. Do you still have all this code there? It builds here.

![image](https://user-images.githubusercontent.com/5719530/98351675-4fce6980-201d-11eb-9233-2d295268f866.png)

**Comment by prashantvidja** [comment]
Oh thanks frikky!
I have not merged your last commit. In my code, there is some line commented.

**Comment by frikky** [comment]
My last commit didn't do anything. The point is, I think you may have edited something which made it stop working, which evidently is on line 704 (as the error in your logs points out)

If you can attach the worker you have or something, I may be of more help :)

**Comment by prashantvidja** [comment]
It's works now. below update made difference.
![image](https://user-images.githubusercontent.com/26060662/98390994-16791680-207c-11eb-9623-eadc46189167.png)

**Comment by frikky** [comment]
Nice! What changes did you make btw? Something usable for other people too? ;)

**Comment by prashantvidja** [comment]
I have increased orborus timeout almost unlimited so want to add some mail alert for the continuous running container.
But look like this orborus timeout thing will do not work for some special cases. so for that, I have decided to write a separate python app.
