### ISSUE TITLE
Default user name password are missing in installation guide.

### ISSUE THREAD

**Issue by dvgaba** [frikky/Shuffle#2]

**Comment by frikky** [comment]
Hey!

I decided to not have a default username and password, but rather have you create your admin user the first time around. 
I'll work on fixing the blank screen, but meanwhile, try visiting /adminsetup rather than /login. 

Adding information to the installation.md about this, thanks!

**Comment by frikky** [comment]
Added more information to the [installation guide](https://github.com/frikky/Shuffle/blob/master/install-guide.md).

TLDR: /adminsetup

**Comment by dvgaba** [comment]
Thanks and blank screen appear for sometime but after that I was able to see login page.

**Comment by frikky** [comment]
@dvgaba Did you get it work properly (log in an play around)?

**Comment by dvgaba** [comment]
I am getting error user data message

**Comment by frikky** [comment]
@dvgaba Run the following from the root directory:

```
git pull
docker-compose down
docker-compose pull
docker-compose up
```

I upgraded the full configuration yesterday.
