### ISSUE TITLE
File handling continuation

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#204]
With the basics of file handling done (#141), there's now a bunch of other use-cases that show up. We should keep building on this list.

- [ ] 1. Different storage mechanisms (S3, Google cloud storage, shared drives...) - use a uniform method
- [ ] 2. Document how it works
- [x] 3. Expose app SDK file handlers
- [x] 4. File listing frontend
- [x] 5. Upload frontend (admin view)
- [ ] 6. Do location caching to prevent upload/download necessities from backend
- [x] 7. Add basic features like timestamps, hashes, encryption methods, compression methods etc.
- [ ] 8. Add optional cleanup on a schedule
- [ ] 9. Add more file information like file type and such

**Comment by dadokkio** [comment]
Adding also filetype as file information could be useful. 
Eg for condition branches if the file is archive, text file or whatever type

**Comment by frikky** [comment]
Added some basic new features to make it easier to test. Will use for malware testing ;)

![image](https://user-images.githubusercontent.com/5719530/108495419-0ee72180-72a9-11eb-9680-ec90ac529a85.png)
