### ISSUE TITLE
Linux capabilities control

### ISSUE THREAD

**Issue by pooki3bear** [frikky/Shuffle#209]
**Is your feature request related to a problem? Please describe.**
Workflows that require additional linux capabilities cannot be created. 

**Describe the solution you'd like**
Workflow configuration should contain input with additional linux capabilities to be used by orborus workers. 

**Describe alternatives you've considered**

**Additional context**
Primary example would be NET_ADMIN for usage of tcpdump and nmap.

**Comment by frikky** [comment]
Uhm, could we expand on this? I've forgotten what we were talking about

**Comment by frikky** [comment]
Closing as there hasn't been any activity. I don't believe it fits our design for workers and Orborus anymore. 

Please correct me if I'm wrong - there are so many possibilities around this.
