### ISSUE TITLE
Apps repo should default to in-use repo

### ISSUE THREAD

**Issue by pooki3bear** [frikky/Shuffle#211]
**Describe the bug**
Every time I import apps from a git repository, it defaults back to the frikky url. 

**To Reproduce**
Click Apps
Click Download From Github

**Expected behavior**
This should display the current URL in use instead.

**Comment by frikky** [comment]
Hey!

This is a great point, but I'm unsure where this configuration should be saved. It's only client side currently (autofilling the field. There's a couple ways I see: user config, org config or browser config. Which do you think?

Keep in mind that a user can be a part of multiple organizations in the future.

**Comment by pooki3bear** [comment]
Org config makes the most sense to me. I could see a single team using a production and development organization that would have a respective branch saved at any given time.

**Comment by frikky** [comment]
Agreed

**Comment by frikky** [comment]
This is kind of done with Orgs, but not being autofilled according to your last input. Would be easily possible as admin, and doing an org wide change to the last one used (check /admin view)

**Comment by frikky** [comment]
This is kind of done with Orgs, but not being autofilled according to your last input. Would be easily possible as admin, and doing an org wide change to the last one used (check /admin view)

**Comment by frikky** [comment]
Closing as this is controlled org-wide
