### ISSUE TITLE
UUID for workflows?

### ISSUE THREAD

**Issue by garanews** [frikky/Shuffle#213]
**Is your feature request related to a problem? Please describe.**
Playing with workflows it happened that I had to download, modify and upload a workflow. During this process same workflow was downloaded multiple times, when upload on the system it was adding as a new workflow keeping same name, so a bit confusing to understand which one is the latest flow:
![image](https://user-images.githubusercontent.com/16938405/101286855-273cb980-37ed-11eb-84a7-23d8960ce9c3.png)

**Describe the solution you'd like**
It would be useful to have an unique identifier for the workflows, so in this way uploading different files, with different names but with same uuid would update the existing workflow

**Describe alternatives you've considered**
Add a datetime of upload near the workflow name.

**Comment by frikky** [comment]
Thanks! This has been on my mind for a long time, but I'm actually not sure how this one should look. What I'm thinking though:
1. When you upload a workflow, make it the selected on, and look "shiny". Some way to identify it easily no matter wat.
2. Make workflows sorted by "last edited time", and add a simple timestamp to it.
3. Unique names. If you upload something with a name that already exists - change it. They do have a UUID, but the name is the same. 
4. An entirely new GUI. I have some things in mind for the 1.0 release, and probably won't do loads of changes before then

Thanks!!

**Comment by frikky** [comment]
I feel like this has been fixed with 0.8.5, as workflows are now sorted and less confusing. The dashboard / GUI update will come at some point though :+1:
