### ISSUE TITLE
Branch Spec for App Import

### ISSUE THREAD

**Issue by pooki3bear** [frikky/Shuffle#216]
**Is your feature request related to a problem? Please describe.**
Workflow import from git allows branch to be specified, app import from git does not.

**Describe the solution you'd like**
I would like to specify branch when importing apps from git.

**Comment by frikky** [comment]
Hmm, I thought this was done already. Apparently not - we only did it for workflows.

I'll set this as a bug, cus it really should be there :+1:

**Comment by frikky** [comment]
Since we talked about config earlier (specify and retain), I guess you're looking for something like this, but to retain what you chose last time:

![image](https://user-images.githubusercontent.com/5719530/101569630-26667c00-39d5-11eb-8f55-49522b35275d.png)

**Comment by pooki3bear** [comment]
Yes, I would like the app and workflow import to be almost identical.

**Comment by frikky** [comment]
Ye, they definitely should be.

**Comment by frikky** [comment]
This has been properly added, including access to edit it organization wide

![Uploading image.png…]()
