### ISSUE TITLE
Strange behaviour on copy workflow

### ISSUE THREAD

**Issue by dadokkio** [frikky/Shuffle#222]
**Describe the bug**
when I copy a workflow the new one has all block duplicated. 
The original workflow is connected while the duplicated blocks are not.
Duplicated blocks are located over original one that until selection are all rounded (start node)

Release: 0.8.5*

Not sure how I can help debugging this :D

**Comment by frikky** [comment]
Hahah, well that was confusing. It was duplicating all actions only when copying

Thanks for the issue :firetruck:

**Comment by frikky** [comment]
Fixed with ghcr.io/frikky/shuffle-backend:0.8.51

**Comment by dadokkio** [comment]
I can confirm the fix is working, just one little note when you copy a workflow with a subflow arrows that interact with subflow are not present in the copy.

**Comment by frikky** [comment]
Thanks @dadokkio! I'll find a fix to this right away :+1:
