### ISSUE TITLE
Cant connect to HTTP

### ISSUE THREAD

**Issue by DanteDevil89** [frikky/Shuffle#231]
i am reading this article
`"https://medium.com/shuffle-automation/getting-started-with-shuffle-an-open-source-soar-platform-part-2-1d7c67a64244"
`
the installation was successful
I'm in a Virtual Machine (vmware workstation) with Ubuntu 18.04. Networking in NAT and relative port forwarding.

![port_forwarding](https://user-images.githubusercontent.com/38345142/105387704-19fd5200-5c16-11eb-9e27-c93237423ed1.png)

if i try to connect on 3001 port (My forwarding 43001) the connection was reset.
If i try to connect on 3443 port (My forwarding 43443) i can create the admin user. But when i create a test "Hello World" the execution is "aborted" (no finished). 
(view image)
![shuffle](https://user-images.githubusercontent.com/38345142/105386693-fd144f00-5c14-11eb-8aba-14b909062d0e.png)

`shuffle-frontend | 10.0.31.205 - - [21/Jan/2021:18:20:45 +0000] "POST /api/v1/workflows/facd7d42-49f5-406e-b694-c449d708ee89/execute HTTP/1.1" 200 151 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
shuffle-backend | 2021/01/21 18:20:46 [INFO] Executionrequests: 1
shuffle-orborus | 2021/01/21 18:20:46 [INFO] fe02f510-47e4-4e9d-a9b2-bf65b297e28f is deployed and to be removed from queue.
shuffle-orborus | 2021/01/21 18:20:46 [INFO] Found container ID ec5ea8ba59f380504f8c764a7ec0aed94cb8e4f06154a554082c765e109ebdc0
shuffle-orborus | 2021/01/21 18:20:46 Identifier: worker-fe02f510-47e4-4e9d-a9b2-bf65b297e28f
shuffle-database | [datastore]
shuffle-orborus | 2021/01/21 18:20:47 [INFO] Container 6bc4aeaa5acb7dad32826b26023d4934f742e8c4c6eca4f212c4fd6c19c97b0d was created under environment Shuffle
shuffle-backend | 2021/01/21 18:20:47 [INFO] API key to abort/finish execution fe02f510-47e4-4e9d-a9b2-bf65b297e28f is correct.
`

what am I doing wrong?

**Comment by frikky** [comment]
Hey! This sounds like an HTTPS issue that I haven't taken into account for the containers and such. 

I'm not sure what exactly happens when you go to 43001 tho. 
- Could you provide logs for when you try to connect?
- Could you provide the docker-compose you've used to get started as well?  

Thanks!

**Comment by DanteDevil89** [comment]
Yes, i can.

version: '3'
services:
  frontend:
    #build: ./frontend
    image: ghcr.io/frikky/shuffle-frontend:0.8.3
    container_name: shuffle-frontend
    hostname: shuffle-frontend
    ports:
      - "${FRONTEND_PORT}:80"
      - "${FRONTEND_PORT_HTTPS}:443"
    networks:
      - shuffle
    environment:
      - BACKEND_HOSTNAME=${BACKEND_HOSTNAME}
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    #build: ./backend
    image: ghcr.io/frikky/shuffle-backend:0.8.3
    container_name: shuffle-backend
    hostname: ${BACKEND_HOSTNAME}
    # Here for debugging:
    ports:
      - "${BACKEND_PORT}:5001"
    networks:
      - shuffle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SHUFFLE_APP_HOTLOAD_LOCATION}:/shuffle-apps
      - ${SHUFFLE_FILE_LOCATION}:/shuffle-files
    environment:
      - DATASTORE_EMULATOR_HOST=shuffle-database:8000
      - SHUFFLE_APP_HOTLOAD_FOLDER=/shuffle-apps
      - SHUFFLE_FILE_LOCATION=/shuffle-files
      - ORG_ID=${ORG_ID}
      - SHUFFLE_APP_DOWNLOAD_LOCATION=${SHUFFLE_APP_DOWNLOAD_LOCATION}
      - SHUFFLE_DEFAULT_USERNAME=${SHUFFLE_DEFAULT_USERNAME}
      - SHUFFLE_DEFAULT_PASSWORD=${SHUFFLE_DEFAULT_PASSWORD}
      - SHUFFLE_DEFAULT_APIKEY=${SHUFFLE_DEFAULT_APIKEY}
      - HTTP_PROXY=${SHUFFLE_HTTP_PROXY}
      - HTTPS_PROXY=${SHUFFLE_HTTPS_PROXY}
    restart: unless-stopped
    depends_on:
      - database
  orborus:
    #build: ./functions/onprem/orborus
    image: ghcr.io/frikky/shuffle-orborus:0.8.0
    container_name: shuffle-orborus
    hostname: shuffle-orborus
    networks:
      - shuffle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SHUFFLE_APP_SDK_VERSION=0.8.0
      - SHUFFLE_WORKER_VERSION=0.8.0
      - ORG_ID=${ORG_ID}
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - BASE_URL=http://${OUTER_HOSTNAME}:${BACKEND_PORT}
      - DOCKER_API_VERSION=1.40
      - HTTP_PROXY=${SHUFFLE_HTTP_PROXY}
      - HTTPS_PROXY=${SHUFFLE_HTTPS_PROXY}
      - SHUFFLE_PASS_WORKER_PROXY=${SHUFFLE_PASS_WORKER_PROXY}
      - SHUFFLE_ORBORUS_EXECUTION_TIMEOUT=600
      - SHUFFLE_BASE_IMAGE_NAME=${SHUFFLE_BASE_IMAGE_NAME}
      - SHUFFLE_BASE_IMAGE_REGISTRY=${SHUFFLE_BASE_IMAGE_REGISTRY}
      - SHUFFLE_BASE_IMAGE_TAG_SUFFIX=${SHUFFLE_BASE_IMAGE_TAG_SUFFIX}
    restart: unless-stopped
  database:
    #build: ./backend/database
    image: frikky/shuffle:database
    container_name: shuffle-database
    hostname: shuffle-database
    ports:
      - "8000:8000"
    networks:
      - shuffle
    restart: unless-stopped
    volumes:
      - ${DB_LOCATION}:/etc/shuffle
networks:
  shuffle:
    driver: bridge


Where can I find the log file?

**Comment by frikky** [comment]
Hey! Could you try this docker-compose and .env file? It's the latest (nightly build), which has fixed tons of problems related to executions the last few months.

Docker-compose:  https://github.com/frikky/Shuffle/blob/launch/docker-compose.yml
.env: https://github.com/frikky/Shuffle/blob/launch/.env

Please get back to me both if it works and if it doesn't. Thanks!

**Comment by CapaoAzul** [comment]
Hey,

First of all, good project and thanks to make it opensource.
I have downloaded the program today, but I cannot execute any workflow, stay in an infinite loop, even with yours (shuffle.io)

Thanks

**Comment by DanteDevil89** [comment]
Hello. sorry if I answer just now.
I inserted your new docker-compose.yml file and now everything works.
I didn't use the .env file

Thanks.

**Comment by frikky** [comment]
> Hello. sorry if I answer just now.
> I inserted your new docker-compose.yml file and now everything works.
> I didn't use the .env file
> 
> Thanks.

Perfect! Updates and such will be made easier going forward :)

**Comment by frikky** [comment]
> Hey,
> 
> First of all, good project and thanks to make it opensource.
> I have downloaded the program today, but I cannot execute any workflow, stay in an infinite loop, even with yours (shuffle.io)
> 
> Thanks

Hey! Did you set it up in Docker and try to run on https://shuffler.io? shuffler.io is broken on purpose right now, and runs an entirely different architecture. It will be back up and running in a month.

Please make a new bug request and outline exactly what you did. We'd love to get you automating :+1: 
https://github.com/frikky/Shuffle/issues/new/choose
