### ISSUE TITLE
delete key behavior while editing app in workflow

### ISSUE THREAD

**Issue by gelim** [frikky/Shuffle#232]
Hi,

I noticed while editing fields of an app in the workflow space, hitting the delete key will wipe the app being edited.
It's really hitting the productivity as you need to refresh the page to recover the deleted component and begin again the app fields edition.

Could it be possible to:
1. Disable delete app handler whenever the focus is not on the workflow graph
2. Have a way to revert a component deleted by mistake like ctrl-z would do

Thanks for the nice project to dig a bit on!
Cheers,

-- Mathieu

**Comment by frikky** [comment]
Hey, and thanks!

This was originally supposed to be a productivity helper, but I do see the fallacies it creates as well. Glad you brought it up, because I've been developing on a mac for the last half year, which doesn't have the key at all. Would it be ok to simply remove that functionality for now, and re-enable it in the future? I'm not sure how widely used it is yet anyway.

CTRL+Z (and similar backwards/forwards behavior) will be a thing we'll implement - it's just not a focus right now.

**Comment by gelim** [comment]
Yeah looks much better to me (and there is still the trash icon).
While I'm at it, out of contexte question related to the splunk app, how results are supposed to be consumed?

I see results like this in the exec log:
```
Name: splunk_1
App: splunk, Version: 1.0.0
Action: SplunkQuery, Environment: Shuffle, Status: SUCCESS
Started: 2021-01-22T15:48:53.000Z
<results preview='1'/>
```

Thanks!

**Comment by frikky** [comment]
Ye, I use the trash icon myself as well. Guess it will have to do for now :)

**Comment by gelim** [comment]
- Have you verified the API is active in Splunk?

Yes, it's working well

- What version of Splunk are you running?
8.0.7

- What are you querying?

Not queen on going in to details about that here, but nothing fancy, events...

Having a quick use-case on app usage would be great to ramp up quickly.
Thanks!

**Comment by frikky** [comment]
Oh for sure. Issue with some old apps (e.g. Splunk) is that I don't have access to environments to test some of them anymore, and we've just recently started properly documenting app usage and creating workflow samples (they're coming)

If you're willing to help me out here, we could possibly help a lot of people with some standardized Splunk usage :+1: 

Mail me at frikky@shuffler.io if you'd like to get into this properly, as Splunk (and SIEM's) are and will forever be important

**Comment by frikky** [comment]
I added this to 0.8.56 which is the latest image that's available
