### ISSUE TITLE
Failed getting apps

### ISSUE THREAD

**Issue by UnicornWhiskers** [frikky/Shuffle#235]
This is a new install of Shuffle  running on Docker desktop on Windows 10 using WSL 2.   Pulled from Git on January 27th 2021.

Initial access to the app appears to work fine and the available apps are populated.  After second login, the apps are no longer appearing.  Front end reports the following error:

TYPEERROR: E.SORT IS NOT A FUNCTION

Checking on the back-end logs:

2021/01/28 16:48:45 [INFO] Getting workflows (ADMIN) for organization 8ebbd399-1e2d-4d45-bdd1-803b87b5894e
2021/01/28 16:48:49 Failed getting apps (getworkflowapps): rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5345082 vs. 4194304)
2021/01/28 16:49:32 Session fdeeadfe-99ad-49bc-961f-b559ecdcd5fe doesn't exist (session auth): datastore: no such entity
2021/01/28 16:49:32 Api authentication failed in getting specific workflow: datastore: no such entity
2021/01/28 16:49:32 Session fdeeadfe-99ad-49bc-961f-b559ecdcd5fe doesn't exist (session auth): datastore: no such entity
2021/01/28 16:49:32 Api authentication failed in getting specific workflow: datastore: no such entity

docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Not sure if there is a setting that can be tuned to increase the allowed message size or if this is an error related to the local host system.  Please let me know if there is any additional information needed to isolate the issue.

**Comment by felipee07** [comment]
Hi,

Latest backend image should fix this issue. 

sudo docker pull ghcr.io/frikky/shuffle-backend:0.8.56

**Comment by UnicornWhiskers** [comment]
Thank you, that fixed the issue.

**Comment by frikky** [comment]
Thanks for helping out @felipee07! Sorry about the issues with old versions.
