### ISSUE TITLE
What are Condtions link is broken

### ISSUE THREAD

**Issue by jasontant** [frikky/Shuffle#237]
Clicking on the "What are conditions" link in the Workflows UI leads to a 404 on shuffler.io.

1. Open a workflow with a connection between two nodes
2. In the Workflows UI, click on the connection between the two nodes
3. On the right-hand details form, click "What are conditions?"
4. Note the target site returns a 404.

Link should send you to a description of conditions. 

![image](https://user-images.githubusercontent.com/13942607/106379314-15087300-6379-11eb-826e-a889bf507db5.png)

![image](https://user-images.githubusercontent.com/13942607/106379342-41bc8a80-6379-11eb-83fb-9d4beba79dbd.png)

**Comment by frikky** [comment]
Hey - thanks for the report! Here's the real link: https://shuffler.io/docs/workflows#conditions

Fixed in last commit :)
