### ISSUE TITLE
Differing action parameter behavior for curly braces vs gtlt

### ISSUE THREAD

**Issue by jasontant** [frikky/Shuffle#238]
When creating a new action via the app UI, using `<>` to wrap parameters seems to result in different behavior than wrapping in `{}`. 

To reproduce this behavior, you will need an API which allows the setting of a filter. I was testing against GitLab's API. 

1. In the App creation UI, add a new action.
2. Set the Name to "GTLT Filter"
3. Set the Request Type to `GET`
4. Set the URL path to `/issues?<filter>`
5. `Submit` the action
6. Add a second action
7. Set the name to "Curly Filter"
8. Set Request Type to `GET`
9. Set the URL path to `/issues?{filter}`
10. `Submit` the action
11. `Save` the App

In the Workflow editor:
12. Add the app 
13. Set the action to `GTLT Filter` 
14. Set filter to `labels=foo`
15. Save & Execute. For me, this results in 20 issues, which do not have the `foo` label.  This is not correct.
16. Change the action to `Curly Filter`
17. Set the filter to `labels=foo`
18. Save & Execute. For me, this results in 1 issue, which is correct.

**Expected behavior**
Behavior should be the same whether using `<>` or `{}` for parameters. The behavior of the `{}` parameters behaved as I expected. 

**Screenshots**
![image](https://user-images.githubusercontent.com/13942607/106383061-979d2c80-6391-11eb-96f9-181949f53ceb.png)

**Comment by frikky** [comment]
Thanks for being so clear about this. I'll have a look at the generator soon-ish. Pretty sure it's a frontend issue.

**Comment by frikky** [comment]
![image](https://user-images.githubusercontent.com/5719530/108389088-9f712380-720f-11eb-8f1b-5f0afa6f679a.png)

Here's the issue in general. It's double-setting when using crocodileface paranthesis. I'll get it fixed :)

**Comment by frikky** [comment]
I fixed it by simply disallowing and autocorrecting all < into { when you add something to the textfield as it's the prioritized way of doing it anyway. This should fix any follow-errors as well.
