### ISSUE TITLE
When passing variable to subflow items are not sent correctly

### ISSUE THREAD

**Issue by dadokkio** [frikky/Shuffle#240]
Trying to pass variable to subflow items are not quoted automatically so, sometimes, you need to wrap them with quotes.
Eg. {"data": $block.items.#, "title": "$exec.header.subject"}
Without quotes the error in the gui is that item is not a valid json.
![image](https://user-images.githubusercontent.com/355183/106442892-27b7a080-647c-11eb-9514-b0e370d48709.png)

**Comment by frikky** [comment]
Hey - can you try this one again with the new setup (0.8.60)?

**Comment by frikky** [comment]
Closing as I believe this is fixed..? :)
