### ISSUE TITLE
Can't see full result in frontend when not JSON

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#241]
Example: long URL returned doesn't show everything

**Comment by frikky** [comment]
Example execution: 
![image](https://user-images.githubusercontent.com/5719530/107205210-dd936980-69fd-11eb-9ee7-c46deee5005e.png)

Probably text wrapping issue

**Comment by amitkinfopercept** [comment]
This is fixed. Please review PR which i sent. 
![image](https://user-images.githubusercontent.com/77421927/107672423-dfd61c00-6cba-11eb-9412-ecfb1b4e5b0d.png)

**Comment by frikky** [comment]
:eyes: Siick!
