### ISSUE TITLE
Workflow play button not shown as finished when workflow execution is aborted

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#242]
After execution of an aborted Workflow stops, the button stays like this which is annoying (gotta click)

![image](https://user-images.githubusercontent.com/5719530/106841579-b279e480-66a2-11eb-89b1-b88f3e94480a.png)

**Comment by amitkinfopercept** [comment]
Workflow play button not shown as finished when workflow execution is aborted

![image](https://user-images.githubusercontent.com/77421927/107679135-32ff9d00-6cc2-11eb-92f3-6cc376931ce7.png)

**Comment by frikky** [comment]
:fire:
