### ISSUE TITLE
Optimize the Shuffle workflow LIST view

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#246]
This is the first view people see when they enter Shuffle in general. It has a list of your previous workflows, listed in order from "last edited". 

* Make it apparent what is in a workflow
* Show sub-workflows, and that they are a subworkflow of another node (lines?)
* Make it possible to list-select workflows and delete etc
* Make scrolling load more workflows (have neverending~ scroll)
* Make it possible to search for internal AND public workflows in the UI 
* Make it possible to 1-click share a workflow

**Comment by frikky** [comment]
![Uploading image.png…]()

Example outline for the UI

**Comment by frikky** [comment]
Maybe utilize entire width of screen?

**Comment by frikky** [comment]
![image](https://user-images.githubusercontent.com/5719530/107883767-3167ec00-6ef1-11eb-97b8-735e1c88981c.png)

More design examples from Figma ^

**Comment by amitkinfopercept** [comment]
![screencapture-localhost-3000-myview-2021-03-15-14_45_28](https://user-images.githubusercontent.com/77421927/111130511-4c378a00-859d-11eb-95a7-553fc6e31a61.png)

The initial draft of the design looks like this

List view
Lazy loading is something that I am working on
