### ISSUE TITLE
worker process created by schedule trigger continuosly running

### ISSUE THREAD

**Issue by prashantvidja** [frikky/Shuffle#257]
**Describe the bug**
when workflow trigger with the schedule trigger it starts a new worker process. I have set a schedule for every 10 sec so it starts with 5  containers every minute. and shuffle auto clean container time is 10 min. 50 containers continuously running for one workflow. If I set 5 workflows with the schedule trigger it will increase too much load.

**To Reproduce**
1. set schedule trigger and set interval 10 sec.
2. check `docker ps` it will show all worker process.
...

**Expected behavior**
1. It should clean the worker process once the new start or workflow execution finished.

**Screenshots**
![image](https://user-images.githubusercontent.com/26060662/107843130-8969fa00-6dee-11eb-8d59-e1c4c16c989b.png)

Note: here I have set 2 min.

**Comment by frikky** [comment]
Hey and thanks for the concern! 

As I started looking at scale for Shuffle I built out this feature a month back or so. I got it to work up to 15 workflows per second with 10~ nodes each before it started having CPU issues with 2 vCPU's and 4Gb RAM. It's not well defined or explained yet, but is an environment variable defined here:

https://github.com/frikky/Shuffle/blob/87e8a5d549780ecf167f62f60ed787c2ef88f630/docker-compose.yml#L69

To enable cleanup, simply pass this to Orborus, and it will tell Workers and Apps to self-cleanup.
```
CLEANUP=true 
```

The issue with this is obvious though: you don't get insight into logs if something goes wrong. Long-term as we pass the logs in the backend itself, that won't be an issue :)

**Comment by prashantvidja** [comment]
Hey Frikky

Thanks for the help.
But it is not working I have added CLEANUP=true in docker-compose.yaml.

Still, it runs for 10 min.

![image](https://user-images.githubusercontent.com/26060662/108311359-f0b2f000-71da-11eb-9dff-f7a60558ef93.png)

**Comment by frikky** [comment]
Hey! Can you try to bump both Orborus and Worker version to 0.8.56? App SDK version doesn't matter here.
I will soon push new builds to master for 0.8.6 which has a lot of the new stable fixes.

![image](https://user-images.githubusercontent.com/5719530/108317440-93a94100-71be-11eb-9542-45165faa05f8.png)

**Comment by prashantvidja** [comment]
Hey Frikky,

I have updated but workflow abort automatically.
![image](https://user-images.githubusercontent.com/26060662/108363018-7609c500-721a-11eb-99d8-fb5af828949c.png)

**Comment by frikky** [comment]
Ok, let's fix that! 
1. Does it work when you run it manually without the Schedule?
2. Can you send some logs from the backend please?

```
docker logs shuffle-backend
```

**Comment by frikky** [comment]
Hey! Any update here? Could you try the latest docker-compose and see if it fixes it? There's been loads of fixes.

https://github.com/frikky/Shuffle/blob/launch/docker-compose.yml

**Comment by frikky** [comment]
Closing as there's been no traction here - feel free to reopen!
