### ISSUE TITLE
Add extensibility possibility to webhooks

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#259]
Webhooks are currently open with a long identifier to avoid issues where it's necessary (UUID). To be extra secure, it would be good to have authentication possiblities through e.g. queries and headers.

**Comment by pemontto** [comment]
Two commonly supported auth methods for webhooks are:
- basic auth
- header auth - providing a custom header and token value

**Comment by frikky** [comment]
More extensibility: webhook to translate params into JSON

**Comment by frikky** [comment]
Tools that use Params for webhooks:
- Rapid7 IDR Alert Webhook
- Sophos Central
