### ISSUE TITLE
Add contributor guidelines

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#263]
It's about damn time

**Comment by dgabriel123** [comment]
Hello, may I work on this? Is there anything specific you would like to include beyond the basic "GIT workflow" stuff?

**Comment by frikky** [comment]
> Hello, may I work on this? Is there anything specific you would like to include beyond the basic "GIT workflow" stuff?

Hey! That's a quick reply, do you got a bot set up? :speedboat: 
The "normal" should be fine, but we have quite a few repos where I'd like to have it for (as seen below from the README)

![image](https://user-images.githubusercontent.com/5719530/108398016-dd267a00-7218-11eb-9ff1-24bb5667ed88.png)

Never seen anyone with a specialization in documentation (bravo :clap:) - we need more people like you!

**Comment by dgabriel123** [comment]
> 
> 
> > Hello, may I work on this? Is there anything specific you would like to include beyond the basic "GIT workflow" stuff?
> 
> Hey! That's a quick reply, do you got a bot set up? speedboat
> The "normal" should be fine, but we have quite a few repos where I'd like to have it for (as seen below from the README)
> 
> ![image](https://user-images.githubusercontent.com/5719530/108398016-dd267a00-7218-11eb-9ff1-24bb5667ed88.png)
> 
> Never seen anyone with a specialization in documentation (bravo clap) - we need more people like you!

No bot, just convenient timing :) OK, I'll add a basic CONTRIBUTING file for this repo, and once you're happy with it, I'll go ahead and add it to the other 4 repos as well!

**Comment by frikky** [comment]
Hey! I moved the CONTRIBUTING guidelines under .github/CONTRIBUTING.md: https://github.com/frikky/Shuffle/blob/master/.github/CONTRIBUTING.md

I also added mostly everything to it about Shuffle in general, meaning we can merge it over to other repositories without much hassle.
