### ISSUE TITLE
Ability to reuse authentication token

### ISSUE THREAD

**Issue by pemontto** [frikky/Shuffle#281]
When an app has to deal with multiple actions from a list, e.g. looping through a list of incidents and adding a comment, it would be useful to be able to reuse a previous authentication token or session.

This is only really an issue where authentication tokens need to be requested, like with OAuth.

Ideally the object could be reused, or the authentication could be handled by a separate singleton object.

**Comment by frikky** [comment]
Moved this over. I'm having the same issue now with an OAuth2 app. It's on the roadmap for March, but it's a tricky one for on-rprem stuff.

Continuation here: https://github.com/frikky/Shuffle/issues/168
