### ISSUE TITLE
Think server is down for docs

### ISSUE THREAD

**Issue by mding5692** [frikky/Shuffle#29]
I see 500 Internal Server Error when move to this page: https://shuffler.io/docs/about

Screenshot:
![Screen Shot 2020-05-22 at 4 16 38 PM](https://user-images.githubusercontent.com/9067177/82706543-df3ab880-9c47-11ea-9191-3857b3db9f80.png)

**Comment by frikky** [comment]
Hey! Checked the logs, and found that only you got this two times in a row (500 error in general). 

I won't look into fixing this right now, as it's on the cloud version.
