### ISSUE TITLE
How do you develop a project in a very large file?

### ISSUE THREAD

**Issue by iiiusky** [frikky/Shuffle#296]
**Describe the bug**
A clear and concise description of what the bug is. If you can't execute a workflow, or an app isn't being created, an app isn't being created etc, please add debug logs (see further down)

**To Reproduce**
Read Golang Code

**Expected behavior**
A description of what you expected to happen.

**How do you develop a project in a very large file?？？？？**

**Comment by frikky** [comment]
Hey! What do you mean very large file? Do you mean e.g. handling files that are 1gb?

**Comment by iiiusky** [comment]
No, I'm talking about project files, such as: https://github.com/frikky/Shuffle/blob/master/backend/go-app/main.go, how to read such a large project file clearly, headache

**Comment by frikky** [comment]
Well, I disagree! I love having it all in one place, and whether it looks like it or not, there is actually a system to it. It will be better as I migrate a lot of it out (e.g. structs) soon tho.

Anyways - to read the file, start from the bottom. This is a webserver afterall, and everything starts in one of these functions:
* main() - Where the webserver basics are defined
* initHandlers() - Sets up the endpoints, pointing to functions
* runInit() - Fixes things between restarts and such. E.g. during startup or upgrades, it cleans up unnecessary things.

**Comment by iiiusky** [comment]
thk.
