### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by gcrahay** [frikky/Shuffle#3]
Hey,

Thamk you for the nice work. What's the license of the Shuffle components?

Regards

**Comment by frikky** [comment]
Thanks for pointing it out. I got a bit more reading to do before I know which one to choose.

If you're good at this sort of thing, DM me on Twitter, as I'd love to talk to someone more experienced about it.

**Comment by NAVHITS** [comment]
I think you should look into something like Apache 2.0 or MIT licenses.

**Comment by aoighost** [comment]
> I think you should look into something like Apache 2.0 or MIT licenses. @frikky

I agree, it would be useful for integration in to other tools

**Comment by frikky** [comment]
Decided on AGPLv3 with help from the MISP team :)

**Comment by aoighost** [comment]
Just a thought, will this mean that apps will have to be distributed under AGPL as well?

**Comment by aoighost** [comment]
The thing that worries me is that if this contaminates apps and workflows running on shuffle, it will scare off people who want to integrate custom internal tools.

**Comment by frikky** [comment]
I'll make sure apps, workflows and documentation have their own repos, and will probably go for MIT. Apps and docs are already seperate, with workflows coming

**Comment by aoighost** [comment]
Good move so far, however the appsdk with the way it's set up looks like it contaminates apps because apps are derivative of it. The appsdk itself needs to be MIT.

**Comment by frikky** [comment]
Noted and good call! As I want the SDK to be as open and available as possible I moved it to  https://github.com/frikky/shuffle-apps, meaning it's MIT licensed.

This shouldn't mean anything for usability right now, as everything is ran through Dockerhub :)
