### ISSUE TITLE
Add a simple Workflow Sharing function

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#310]
As we aim to let users share their use-cases with others, we need a way to have them be shared. This is already doable with Apps are mainly Private (per user) when they're made, and then have to be shared.

For apps, you can by example click a single button to change this, which releases it to anyone.

**Comment by frikky** [comment]
Done! You can click "Publish workflow" and it's immediately available to anyone

**Comment by prashantvidja** [comment]
How to make it private again?

**Comment by frikky** [comment]
> How to make it private again?

Assuming you released the "DNS tunnel" one? I'll make it private manually for now. If you're signed in with cloud, we'll make you able to control it, but if you release from onprem, you'll have to tell us :P

**Comment by frikky** [comment]
(looks super sick btw!)

**Comment by prashantvidja** [comment]
Does it send all apps as well?

**Comment by prashantvidja** [comment]
Yes this is not good.

**Comment by frikky** [comment]
> Does it send all apps as well?

I disagree, and think it in fact is good. Anything to be able to share more easily is good, and part our mission. I initially just removed it from our search engine, but now just made it non-public. Cache should clear up soon.

In the future, this will all of course be better. I've added a basic disclaimer for it for newer versions, and added a new issue to handle takedowns and such. Our site isn't super active yet, so I just checked, and no one got to see it except me ;)

Disclaimer version 1:
![image](https://user-images.githubusercontent.com/5719530/113566894-da87b480-960d-11eb-9b42-b22bf1afba8f.png)

**Comment by prashantvidja** [comment]
Thank you very much.

**Comment by prashantvidja** [comment]
Did it remove all inputs before sending?

**Comment by frikky** [comment]
> Did it remove all inputs before sending?

Not all, but most. There's two sanitizers, plus an entropy checker and removal of authentication in general. If you'd like, I can send you the workflow, then you can import it and have a look for yourself if there's any issue. Happy to improve the sanitizers, as this will become critical!

**Comment by prashantvidja** [comment]
Yes please send

**Comment by frikky** [comment]
> Yes please send

Where? I'll send you the tiny things I found as well, which I've updated in the newer sanitizer. No passwords or usernames or anything like that was shared.

**Comment by prashantvidja** [comment]
My id is prvidja10@gmail.com
