### ISSUE TITLE
Worker sometimes fails over to registry.hub.docker.com 

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#317]
It's gotta have something to do with non-unique ID's or something. Will dig deeper.

**Comment by felipee07** [comment]
[debug.log](https://github.com/frikky/Shuffle/files/6217970/debug.log)

2021/03/28 02:28:03 [WARNING] Container CREATE error: Error response from daemon: No such image: frikky/shuffle:Shuffle-Tools_1.0.0

**Comment by frikky** [comment]
Thanks for the log! Indeed looks like it has to do with non-unique names

**Comment by frikky** [comment]
Hey @felipee07! Please try version 0.8.70 of the Worker (set it in your docker-compose for Orborus). I've added another layer of randomization to execution names, and changed order of execution to skip a step. 

![image](https://user-images.githubusercontent.com/5719530/112795612-0e406880-9069-11eb-82b7-650bbf39ac71.png)

**Comment by felipee07** [comment]
0.8.70 fix this specific problem, but introduces another. Now, if I use branches, a single task will be run multiple times.

**Comment by felipee07** [comment]
Task
![image](https://user-images.githubusercontent.com/2327625/112921961-0a9cf800-90e2-11eb-8a7f-55b6fd9420aa.png)


Result !
![image](https://user-images.githubusercontent.com/2327625/112921845-dc1f1d00-90e1-11eb-95fa-a9fcd9995b82.png)

**Comment by frikky** [comment]
Ok thanks, now that is progress but definitely something I'll work on fixing. I guess the queue system got screwed up.

**Comment by frikky** [comment]
This seems to have been fixed, and is related to #323 and new Worker updates.
