### ISSUE TITLE
Shuffle users unable to run workflow created by another user

### ISSUE THREAD

**Issue by arnydo** [frikky/Shuffle#330]
When multiple users are using the same instance, they are unable to run workflows created by another user.

The UI shows:
![image](https://user-images.githubusercontent.com/11653079/113445231-7c679100-93c3-11eb-9be6-ddc9bb939999.png)

The logs show:
`Wrong user (username@domain.com) for workflow x.`

A user can copy a workflow made by another user and run it that way...

Version: `0.8.71`

**Comment by frikky** [comment]
Transferred to Shuffle as this is a backend issue

**Comment by frikky** [comment]
Fixed. Will be a part of 0.8.72
