### ISSUE TITLE
Cannot delete hotloaded shuffle-apps

### ISSUE THREAD

**Issue by arnydo** [frikky/Shuffle#331]
When working with hotloaded apps, in particular, copies of "built-in" apps such as `OWA`, I am unable to delete it when it is no longer needed. 

Receiving the following error:
`shuffle-backend | 2021/04/02 18:41:29 Wrong user (user@domain) for app owa test when DELETING app`

Version: `0.8.71`

**Comment by frikky** [comment]
This is also probably a backend issue. Transferred.

**Comment by frikky** [comment]
Added possibility for Org admins to delete apps without owners.

PS: There may exist multiple of each, so even though it may not look like deletion works at first, it's because there are duplicates (not always being overwritten)
