### ISSUE TITLE
webhook not working on the duplicated workflow

### ISSUE THREAD

**Issue by prashantvidja** [frikky/Shuffle#337]
**Describe the bug**
I have duplicated the workflow, But on the workflow webhook on the duplicated workflow not working.

**To Reproduce**
1. Create a workflow with the webhook trigger.
2. Duplicate it and make a new workflow.
3. Edit the newly created workflow and start the webhook or remove it and add a new webhook.
4. Trigger it using POST API.
getting below result.
`{"success": false}`
...

**Expected behavior**
It should work.

**Debug logs**
```
2021/04/07 07:47:33 Failed getting hook e2cb38de-e601-44ab-8289-401f3c240304 (callback): datastore: no such entity
```

**Comment by frikky** [comment]
Thanks! Will check it out. Guessing it has to do with some lingering ID for the workflow or something.

**Comment by frikky** [comment]
Yep, it was indeed a simple issue with ID's not being replaced. Automatically fixed upon saving and importing in the future.

**Comment by prashantvidja** [comment]
Hey Frikky,

Also, I got one issue with the newly created workflow as well.
I have created a workflow with webhook after removing a default test node from the workflow.
I am not able to trigger webhook getting the below error.
```json
{"success": false, "reason": "Workflow action 40447f30-fa44-4a4f-a133-4ee710368737 doesn't exist in workflow"}
```
and in backend logs, I am getting.

> 2021/04/10 04:25:15 [INFO] Execution source is webhook for execution ID 907fc536-5467-4bd2-83df-13792432863a in workflow 3bbaf610-8746-4a30-bd67-dd1e46eee8c3
> 2021/04/10 04:25:15 [INFO] New startnode: 40447f30-fa44-4a4f-a133-4ee710368737
> 2021/04/10 04:25:15 [ERROR] Startnode 40447f30-fa44-4a4f-a133-4ee710368737 doesn't exist!!

Please check this out.
I am not able to create a new workflow till that time.

Thanks

**Comment by frikky** [comment]
Made a new issue for it!
