### ISSUE TITLE
[issue] Loosing workflow view for normal user after container restart. 

### ISSUE THREAD

**Issue by azgaviperr** [frikky/Shuffle#339]
**Describe the bug**
Created workflow under a not admin user sometimes disapear from his interface while still available under the admin view.

**To Reproduce**
1. Create a Workflow under a non admin user
2. run a docker-compose down and up
3. See that workflow are missing on the user view but not in the user admin view.
...

**Expected behavior**
Not loosing our workflow over restart of containers

**Comment by frikky** [comment]
Thanks! Everything for users (compared to admins) hasn't been 100% ironed out yet. We'll make it happen soon enough ;)

**Comment by frikky** [comment]
This was a problem with the Init script which migrated users and workflows if there was anything wrong with the setup.
