### ISSUE TITLE
[Bug] Shuffle tools SMS doesn't work with European phone

### ISSUE THREAD

**Issue by azgaviperr** [frikky/Shuffle#340]
Tried the cloud feature and sending SMS is not working for European phone numbers.

**Comment by frikky** [comment]
Transferring as this is a backend issue, not actually an app issue (even though it's used as an app)

Thanks, I'll check out the settings!

**Comment by frikky** [comment]
Seems like it's working based on our test, so I'm thinking it's either of these;
- Your API key doesnt have access to send SMS (there's an amount limit, maybe it wasnt set)
- The hybrid connection is wonky and didn't work (depends where it's executed from)

**Comment by azgaviperr** [comment]
was executed from the onpremise shuffle instance

**Comment by frikky** [comment]
![image](https://user-images.githubusercontent.com/5719530/114281954-964b4880-9a41-11eb-983d-0daeb41c05b0.png)

Your limit was set to 0, thankfully not a Shuffle or SMS provider bug. Try it again, I've given you some to play around with! :D

Good thing here is we'll also get to test the counters and such.
