### ISSUE TITLE
[BUG] Python3 Playground APP - Calling a PHP file

### ISSUE THREAD

**Issue by mcoreia** [frikky/Shuffle#341]
**Describe the bug**:
 When using the Python3 Playground it can't run an imported php file. Im using the subprocess.call function from subprocess module.

![image](https://user-images.githubusercontent.com/81681817/114073840-a5909180-989b-11eb-9071-a7bf33ea8dbb.png)

**To Reproduce**:
1. Import the php file to /src folder where is the app.py
2. Edit the app.py and create a function to run the php file
3. Update local apps
4. Run it on a workflow

**Expected behavior**:
Run the php file and pass the arguments.

**Extra Info**:
Json:
```
{
"farg": "something",
"sarg": "something too"
}
```

Function:
```
import subprocess
...
def run_me_2(self, json_data):
        farg = str(json_data['fargr'])
        sarg = str(json_data['sarg'])

        subprocess.call(["php", "myfile.php", farg, sarg])

        return json_data 
```

PHP File:
```
<?php
echo $argv[1];
echo $argv[2];
?>
```

**Comment by frikky** [comment]
I just tried this, and the files are imported. After looking at the issue again, I wonder whether the issue may be with php itself. Are you sure you have PHP available inside the app? The issue here doesn't say "myfile.php" missing, but "php" itself.

I tested it by adding a simple file to the shuffle-tools app, then running the "Exec bash" command with "ls" and "cat <filename>". Both worked well, and other files are in the same folder as the app.py.

**Comment by mcoreia** [comment]
Thanks, I forgot about that. The php file needs the php-cli installed to execute the file. Any idea about how to install a php interpretor using the python3 playground?

**Comment by frikky** [comment]
It's all about the Dockerfile. I'm thinking what you need is to add this to the bottom of it, [based on this url](https://www.cyberciti.biz/faq/how-to-install-php-7-fpm-on-alpine-linux/?__cf_chl_jschl_tk__=3d8d562e6cbfab55d6ef57e98d7555ed164d58bc-1618141153-0-Ab2o1DIY0MyaIh4BDDwmhrLWbZHXKh_5eAO3-n5Ijc4aPZRCSHM6qeQsXocTxz8MCp07dlACt-H3pc0RioqrZHZUVGAa3fG2yCYNP6wLefsdIpU4aiN2LFmoP8hITQphYDH-3pu-HcFztnE30K5naNGJsTr-sYEz6rqgKaBO3L4L4p6dbUPQKzA7hOvmJhMXq1FZajJHjecYTrplbnrb5Q9JPPmm-q00P1-bitXk0RXaHkFT1FUp2znJC3gj1AATq_GCmsNq6H84FoOdfPavyps4Z5xtrm1hKhBIHKZQj6fzR2TA8NCu5Tg6Uv2Q71n8fIXSPJD-SbrZTD2eOq5lUQggVpaXRB0gjJg58rnkBRQQQFmuUZDOvVgq42tG4fSYBiH0E70jL3-CApbESpsPKv5D4595-mDVXyaSTz_wfE_G3-obUBu3tBrlGsAcEg0FvbGqqqCURiFjNBOLjqoHkPJgVtlmdPI3F445MT6pT0wwzAKyeRyWYC78ce5zAogj4g).

```
apk add php7 php7-fpm php7-opcache
```

**Comment by mcoreia** [comment]
Ok, I'll try it and then i give you feedback. Thanks!

**Comment by mcoreia** [comment]
@frikky you can close this issue, it worked! You just need to add the following line to the bottom of the Dockerfile:
```
RUN apk add php7 php7-fpm php7-opcache
```

Thanks!

**Comment by frikky** [comment]
> @frikky you can close this issue, it worked! You just need to add the following line to the bottom of the Dockerfile:
> 
> ```
> RUN apk add php7 php7-fpm php7-opcache
> ```
> 
> Thanks!

Cool, glad it worked!
