### ISSUE TITLE
Use the real trigger node, not saved

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#342]
Hey Frikky,

Also, I got one issue with the newly created workflow as well.
I have created a workflow with webhook after removing a default test node from the workflow.
I am not able to trigger webhook getting the below error.
```json
{"success": false, "reason": "Workflow action 40447f30-fa44-4a4f-a133-4ee710368737 doesn't exist in workflow"}
```
and in backend logs, I am getting.

> 2021/04/10 04:25:15 [INFO] Execution source is webhook for execution ID 907fc536-5467-4bd2-83df-13792432863a in workflow 3bbaf610-8746-4a30-bd67-dd1e46eee8c3
> 2021/04/10 04:25:15 [INFO] New startnode: 40447f30-fa44-4a4f-a133-4ee710368737
> 2021/04/10 04:25:15 [ERROR] Startnode 40447f30-fa44-4a4f-a133-4ee710368737 doesn't exist!!

Please check this out.
I am not able to create a new workflow till that time.

Thanks

_Originally posted by @prashantvidja in https://github.com/frikky/Shuffle/issues/337#issuecomment-817076176_

**Comment by prashantvidja** [comment]
If you fixed then please push.
So i can test other issues.

**Comment by frikky** [comment]
> If you fixed then please push.
> So i can test other issues.

Hey! This was only half done. If you get this issue, the workaround is to re-create the trigger.

**Comment by prashantvidja** [comment]
@frikky Not working by re-creating trigger.

Thanks

**Comment by frikky** [comment]
> @frikky Not working by re-creating trigger.
> 
> Thanks

Hey! Please upgrade to 0.8.76 - it fixes the issue of the worng. Recreating the webhook and saving should work though.

Here's the compose file: https://github.com/frikky/Shuffle/blob/launch/docker-compose.yml

**Comment by frikky** [comment]
I believe this is fixed, and haven't had an issue for Schedules or Webhooks since 0.8.70. Will reopen if we find issues.
