### ISSUE TITLE
Unable to  activate apps in Shuffle

### ISSUE THREAD

**Issue by hermanmaleiane** [frikky/Shuffle#343]
**Work Environment** 

**OS**: Centos 7
**docker version**
Docker version 20.10.5, build 55c4c88

**Describe the bug**
 I'm not able to add apps in  Shuffle because I'm getting the below.
Error: Error in Docker build: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**To Reproduce**
1. Run installation based on  docker-compose  https://github.com/frikky/Shuffle/blob/launch/docker-compose.yml
2. Try to add App and get the error. 

**Expected behavior**
Go to the option Apps and be able to add APPS
**Screenshots**
![image](https://user-images.githubusercontent.com/13849459/114312082-a7ec2900-9af1-11eb-831d-3612063cb34e.png)

** Debug logs **
**Logs when the service is starting from docker-compose.**

shuffle-orborus | 2021/04/11 16:01:31 [INFO] Pulling image ghcr.io/frikky/shuffle-worker:0.8.71
shuffle-orborus | 2021/04/11 16:01:31 [ERROR] Failed getting image ghcr.io/frikky/shuffle-worker:0.8.71: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=ghcr.io%2Ffrikky%2Fshuffle-worker&tag=0.8.71": dial unix /var/run/docker.sock: connect: permission denied
shuffle-orborus | 2021/04/11 16:01:31 [INFO] Finished configuring docker environment
shuffle-orborus | 2021/04/11 16:01:31 [INFO] Running with HTTP proxy http://10.2.24.42:3128 (env: HTTP_PROXY)
shuffle-orborus | 2021/04/11 16:01:31 [INFO] Running with HTTPS proxy http://10.2.24.42:3128 (env: HTTPS_PROXY)
shuffle-orborus | 2021/04/11 16:01:31 [INFO] Waiting for executions at http://shuffle-backend:5001/api/v1/workflows/queue
shuffle-orborus | 2021/04/11 16:01:31 [INFO] Looking for old containers (zombies)
shuffle-orborus | 2021/04/11 16:01:31 [ERROR] Failed creating Containerlist: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json?all=1&limit=0": dial unix /var/run/docker.sock: connect: permission denied
shuffle-orborus | 2021/04/11 16:01:31 [ERROR] Error getting containers: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json?all=1&limit=0": dial unix /var/run/docker.sock: connect: permission denied
shuffle-orborus | 2021/04/11 16:01:31 [WARNING] Failed making request: Get "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp: lookup shuffle-backend on 127.0.0.11:53: server misbehaving

**Comment by frikky** [comment]
Hey! You mentioned this was fixed on Discord. Can you tell us how you did it?

Thanks!

**Comment by hermanmaleiane** [comment]
I just added the privilege's to run.


 image: ghcr.io/frikky/shuffle-backend:0.8.71
    container_name: shuffle-backend
    hostname: ${BACKEND_HOSTNAME}
    **privileged: true**
    # Here for debugging:
    ports:
      - "${BACKEND_PORT}:5001"
    networks:
      - shuffle

**Comment by frikky** [comment]
Thanks! Didn't know about this option.
