### ISSUE TITLE
[Feature Request] Add possibility to replay action if node fails

### ISSUE THREAD

**Issue by azgaviperr** [frikky/Shuffle#345]
**Is your feature request related to a problem? Please describe.**
It could be great to add a function to be able to replay segment or all part of workflow in cas of a node failure. A bit like the rerun option but either localized to a node or/and with mass replay capabilities. 

To illustrate. Imagine a SIEM sending alert on Shuffle webhook. On the process there is a thehive node. Unfortunatly thehive webhook is unavailable because of issues. Alert will be lost, until someone replmay the all workflow manually. In case of a multi org, this could take some time and clicking. 

**Describe the solution you'd like**
Maybe some way to check if node is active again on schedule, if up then send back the backlog of failded execution. After some number of retry there is no more automatic control and action will have to be done manually. 
Some way to be alerted of issue should be added.

**Comment by frikky** [comment]
This is definitely something we'll need, and shouldn't be too hard to do. E.g. saying it will retry like 5 times or something. 

Easy: Replay an app, or the entire workflow
Harder: Replay A PART of the workflow

Where do you think this should be configured? On the trigger or the workflow itself?

**Comment by frikky** [comment]
Added a start to this. Here's the new cleanup system (basic):
Every 10 minutes, run a schedule which checks for old executions to abort, AND old executions to rerun.

IF the execution is more than 30 minutes old and still executing, it gets stopped.
IF the execution is more than 9.5 minutes old and still executing, it gets requeued (continuing from where it stopped).

This way, a workflow will always retry 3 times before being stopped, and a max time to run is 30 minutes.
