### ISSUE TITLE
Implement programmatic build container names

### ISSUE THREAD

**Issue by SynAck3** [frikky/Shuffle#359]
During container builds, Shuffle currently leverages default docker random names for containers.  This can make identifying the specific build container a certain amount of guess work. 

It would be useful if Shuffle implemented a programmatic naming scheme for its build containers.  Similar to how we have shuffle-FOO for the core containers, I would like to propose a consistent, predictable name that would be easily identifiable, such as shuffle-build-_MYAPP_-_MYVER_.

**Comment by frikky** [comment]
Tried to find the option while working on proxy config for this in [here](https://github.com/docker/go-docker/blob/4daae26030ad00e348edddff9767924ae57a3b82/api/types/client.go#L142) but I wasn't able to find the image name specifier for builds - just labels and tags.

**Comment by SynAck3** [comment]
> Tried to find the option while working on proxy config for this in [here](https://github.com/docker/go-docker/blob/4daae26030ad00e348edddff9767924ae57a3b82/api/types/client.go#L142) but I wasn't able to find the image name specifier for builds - just labels and tags.

TIL. You can’t actually name build containers.  There’s a docker forum post on it [here](https://forums.docker.com/t/name-docker-build-container/24060/5)

**Comment by frikky** [comment]
> > Tried to find the option while working on proxy config for this in [here](https://github.com/docker/go-docker/blob/4daae26030ad00e348edddff9767924ae57a3b82/api/types/client.go#L142) but I wasn't able to find the image name specifier for builds - just labels and tags.
> 
> TIL. You can’t actually name build containers. There’s a docker forum post on it [here](https://forums.docker.com/t/name-docker-build-container/24060/5)

Thanks! That simplifies it
