### ISSUE TITLE
Screen is Blank (Almost during initial login)

### ISSUE THREAD

**Issue by pmisner** [frikky/Shuffle#361]
I used the setup notes in the blog. I managed to get everything up after changing the port on my Splunk instance from 8000 to 8080. 
Now, when I come to the main page, it's black, except for about and login. If I mess around with the page, I sometimes will see the login screen for a millisecond or so, then it goes black again. Using Virtualbox, Ubuntu 20.04.  I'm not using any custom backgrounds on Firefox.  OK, this is a bit freaky, but after about 10 minutes or so, the page refreshed and gave me a normal login account. I did not get the initial admin account. 

![image](https://user-images.githubusercontent.com/19804954/116156984-39df5e80-a6ba-11eb-9185-c1cc4213cc1f.png)

**Comment by pmisner** [comment]
Just tried it in Chrome. Same result.

**Comment by frikky** [comment]
Never seen this before - thanks for the info! Could you try this docker-compose instead: https://github.com/frikky/Shuffle/blob/launch/docker-compose.yml

It uses all the latest versions of Shuffle, and we've fixed a lot of issues since the last major release on the master branch.

**Comment by frikky** [comment]
Hey @pmisner, did this resolve the issue?

**Comment by frikky** [comment]
Hey @pmisner - did you get time to check it out further after our chat?

**Comment by frikky** [comment]
I realized this has to do with the Nginx mimetype choice when loading .js files. 

Moving to 1.0 as it's an annoyance more than anything else
