### ISSUE TITLE
http app missing

### ISSUE THREAD

**Issue by falcorocks** [frikky/Shuffle#363]
Hi @frikky , we are happily using your shuffle!

But today we updated from 0.8.0 to 0.8.71 and suddenly the HTTP app that we heavily relied upon for our playbooks is gone.
How do we perform basic http requests now? Can we re-add it ourselves? Was this intended?

**Comment by falcorocks** [comment]
@thetez

**Comment by azgaviperr** [comment]
Hello, 

The application is still available. I recommend you to update to the 0.8.76 and force update the app. 
![image](https://user-images.githubusercontent.com/7451354/116703403-87b1da80-a9ca-11eb-8faa-f5ac741d8bd3.png)

**Comment by falcorocks** [comment]
thanks guys!
