### ISSUE TITLE
Issues connecting Shuffle to Qradar

### ISSUE THREAD

**Issue by hermanmaleiane** [frikky/Shuffle#364]
**Describe the bug**

Hi Team,
Hope you are doing well.
I trying to get Shuffle working with QRadar but I'm facing some issues.

**To Reproduce**
1. Create the workflow in Shuffle
![image](https://user-images.githubusercontent.com/13849459/116850313-bc06e000-abf0-11eb-9eef-b51df22e7ff3.png)

Parameters for authentication 
![image](https://user-images.githubusercontent.com/13849459/116850463-fff9e500-abf0-11eb-84db-85ea6589ef53.png)

**Expected behavior**
I was expecting to connect to qradar and get offenses. 

Error
![image](https://user-images.githubusercontent.com/13849459/116851537-d17d0980-abf2-11eb-8e62-c55e052b1ab9.png)

I don't much details on shuffle-backend logs.

Thanks in advance

**Comment by frikky** [comment]
ooh, this looks like an unexpected issue from the 0.8.76 update. The point is to introduce URL's into every app authentication, where something obviously went wrong here somehow.

I'll check it out tonight and get back to you.

**Comment by hermanmaleiane** [comment]
Hi @frikky . 
Thanks for answering. 
I will be waiting.

**Comment by frikky** [comment]
Can you please follow these steps:
1. Go to https://shuffler.io/apps/4fe358bd204f672d37c55b4f1d48ccdb
2. Download the app: ![image](https://user-images.githubusercontent.com/5719530/116891691-4bcb7f00-ac2f-11eb-99c6-b401fc3ac75f.png)
3. Go to your open source version and upload it: ![image](https://user-images.githubusercontent.com/5719530/116891769-669df380-ac2f-11eb-8ab4-512441ce338f.png)
4. Change the name of the app slightly. E.g. to something like "QRadar API"
5. Rebuild it! ![Uploading image.png…]()

Put this new one in a workflow. You may need to reauthenticate, but it should work, as it's built from scratch.

**Comment by hermanmaleiane** [comment]
Hi @frikky.

Sorry for bothering you again.
I got stucked on point 3. 
I'm Not able to upload the downloaded file.

![image](https://user-images.githubusercontent.com/13849459/116897166-3eb18e80-ac35-11eb-81e7-8287a6d88365.png)

The line that the error is pointing.

![image](https://user-images.githubusercontent.com/13849459/116897329-6bfe3c80-ac35-11eb-8f1c-1453c241ed9b.png)

I'm not sure what's going wrong in my side.

**Comment by frikky** [comment]
Looks like https://shuffler.io is exporting the wrong data.
I'll fix shuffler.io export later - nice bug find :)

Sending a working version on Discord.

**Comment by hermanmaleiane** [comment]
Hi @frikky .
Thanks for your support.
Using the qradar.yaml you provided on discord worked.
I have success, but with strange output. I'm not getting the offenses, Any tip?

![image](https://user-images.githubusercontent.com/13849459/116966564-c25c9100-acb0-11eb-900d-049184d09fa7.png)

Thanks in advance.

**Comment by frikky** [comment]
What version of QRadar are you running?

**Comment by hermanmaleiane** [comment]
![image](https://user-images.githubusercontent.com/13849459/116976295-3d2da800-acc1-11eb-89d9-5c53b091ef2b.png)

**Comment by frikky** [comment]
Ok, so it should be valid (we're based on API version 15.0) then

Did you specify the URL like this? https://<host_ip>/api

**Comment by hermanmaleiane** [comment]
Hi,

Actually I'm using something like this on URL: 
https://qradar-09.test.com/

I'm not sure how to get the missing part but i will try to find.

**Comment by frikky** [comment]
Ah, simply change the URL to https://qradar-09.test.com/api

**Comment by hermanmaleiane** [comment]
It's working now. Thank you @frikky.

 Dealing with authentication issues. 
I'm sure i have provided the SEC token when i created the app. 
![image](https://user-images.githubusercontent.com/13849459/116980346-67ce2f80-acc6-11eb-9e0d-958c1568239d.png)

**Comment by frikky** [comment]
> It's working now. Thank you @frikky.
> 
> Dealing with authentication issues.
> I'm sure i have provided the SEC token when i created the app.
> ![image](https://user-images.githubusercontent.com/13849459/116980346-67ce2f80-acc6-11eb-9e0d-958c1568239d.png)

Can you try to reauthenticate?

**Comment by hermanmaleiane** [comment]
Yes i did that. 

When i choose API Key there is e Text Field with place holder (Field name not token).
I'm putting the token there but it says juts the field. Per default it is SEC.
![image](https://user-images.githubusercontent.com/13849459/116991330-ad91f480-acd4-11eb-9a84-d5f45d397416.png)

**Comment by frikky** [comment]
Ah, I understand! Please put "SEC" in that field, then save it again.

Then when you authenticate the app inside a workflow, you put your API-key in there. The part you're showing here is just for defining the app itself, not for authenticating. The authentication is done in workflows themselves:

![image](https://user-images.githubusercontent.com/5719530/116993626-09aa4800-acd8-11eb-8c4c-d342d9aa9aa2.png)

**Comment by hermanmaleiane** [comment]
Ok thanks. Please check this error now.

![image](https://user-images.githubusercontent.com/13849459/117001259-6874bf00-ace2-11eb-93c7-20f0c821e6e6.png)

I put my API Key here but it says API KEY is missing. 
When i open the AUTH dialog box again it's empty. 

![image](https://user-images.githubusercontent.com/13849459/117001486-b38ed200-ace2-11eb-960b-2731ae1521d1.png)

**Comment by frikky** [comment]
Let's do a do-over of the authentication process. I'll make sure to document the confusing parts more in detail in the UI for future reference as well. About authentication items in general; that the fields disappear is correct - it's possible to run the apps "without" authentication. When you open a new auth window, or try to edit, you shouldn't see your api-key either.

This is just one of the ways Shuffle protects your credentials, as we don't want anything else to get access to your credentials outside of apps. They can NOT be rewritten, just overwritten.

**To refresh all QRadar authentication:**
1. Go to the /admin view under "App Authentication"
2. Find any app that is related to QRadar. Delete them.
3. Go back to the workflow (refresh the window), then click the app again. 
4. Create a new authentication again
5. SAVE!
6. Test it the workflow

**Comment by hermanmaleiane** [comment]
So much thanks. I think it solved.

Now it seems like Qradar is not exposing the de API and is raising this error:
I think it's not on shuffle side now. What do you think?

![image](https://user-images.githubusercontent.com/13849459/117004952-f6eb3f80-ace6-11eb-8f6f-4fb043ae9652.png)

**Comment by frikky** [comment]
> So much thanks. I think the auth part is solved.
> 
> Now it seems like Qradar is not exposing the de API and is raising this error:
> I think it's not on shuffle side now. What do you think?
> 
> ![image](https://user-images.githubusercontent.com/13849459/117004952-f6eb3f80-ace6-11eb-8f6f-4fb043ae9652.png)

Can you check the API-docs based on this? https://www.ibm.com/docs/en/qsip/7.4?topic=SS42VS_7.4/com.ibm.qradar.doc/c_rest_api_whats_new.html

It's basically saying you should go to /api_doc in your instance.

**Comment by hermanmaleiane** [comment]
check it @frikky. 

I was able to retrieve the offenses testing from api docs.

![image](https://user-images.githubusercontent.com/13849459/117006712-0ec3c300-ace9-11eb-9729-2b69a3c48de7.png)

**Comment by frikky** [comment]
Well, that's confusing. It's literally saying the exact endpoint we are using, which you confirmed to work, is missing :face_with_thermometer:

So. Confused. 

Can you try that curl request with the HTTP app? Just copy it and run: 
![image](https://user-images.githubusercontent.com/5719530/117008090-a675e100-acea-11eb-9d23-be6870679640.png)

**Comment by hermanmaleiane** [comment]
![Uploading image.png…]()

**Comment by frikky** [comment]
ah, please add -k to it. This will disable SSL certificate validation, e.g:

```
curl https://google.com -k
```

**Comment by hermanmaleiane** [comment]
This one is related to auth i think, what makes sense.
![image](https://user-images.githubusercontent.com/13849459/117011843-92cc7980-acee-11eb-83ad-cb58e4f31feb.png)

**Comment by frikky** [comment]
You, now add something like this to it (change APIKEY for yours):

```
-H 'SEC: APIKEY'
```

**Comment by hermanmaleiane** [comment]
I have something like:
curl  https://qradar-tes.com/api/siem/offenses -k -H 'SEC: 12b61e37-'

![image](https://user-images.githubusercontent.com/13849459/117014196-db853200-acf0-11eb-9c3a-ffb1abc4c738.png)

**Comment by frikky** [comment]
Ok, so this probably means you got what you were looking for. It's 49 alerts afterall, and Shuffle has a max capacity of 0.5Mb per result for now, so I guess it's above that.

Alright, so that means the only logical issue is with the app itself, which gets built by Shuffle. I'm doing some changes to the App Builder itself right now, and I'll get back to you here tomorrow with a new version of Shuffle that should be building everything correctly

**Comment by hermanmaleiane** [comment]
Oh awesome @frikky . 
I will be waiting.

**Comment by hermanmaleiane** [comment]
Hi @frikky .
How are you?
Any updates on this matter?

**Comment by frikky** [comment]
> Hi @frikky .
> How are you?
> Any updates on this matter?
> 
> 
> 
> 
Hey! I'll push updates tonight. Last week was a bit hectic 🙃

**Comment by frikky** [comment]
Hey @hermanmaleiane! 

I was working on another issue related to the whether the correct apps are loading or not today, and came across a similar issue, leading me to fixing it. Have you had the chance to look at it again? If you'd like, we can have a chat next week to further improve the QRadar setup.

**Comment by hermanmaleiane** [comment]
Sadly I didn’t try it again since I had the reported issue. 
Sure, we can have a chat @frikky. I available.

**Comment by frikky** [comment]
> Sadly I didn’t try it again since I had the reported issue.
> Sure, we can have a chat @frikky. I available.

Can you please send me an email at frikky@shuffler.io? Let's get it scheduled :)

**Comment by hermanmaleiane** [comment]
Hi @frikky. 
Already sent you the email.

**Comment by frikky** [comment]
I believe this has been fixed based on our conversations :)

**Comment by hermanmaleiane** [comment]
hi @frikky 
Hope you are doing well. 

Last week i tested with success but today I'm facing some issues with authorization- SEC

**The error**
![image](https://user-images.githubusercontent.com/13849459/123818958-afa1b980-d8f9-11eb-98cc-6d10c07290c4.png)

**Configuration** 
![image](https://user-images.githubusercontent.com/13849459/123818808-96990880-d8f9-11eb-8e15-4927f9ffe656.png)

**Comment by a-ml** [comment]
Hello @hermanmaleiane 

Did you solved your problem?

I was facing the same issue, followed the steps and I managed to get QRadar App authenticating to the QRadar and fetching the information, now the remaining steps in the workflow are failing.

<img width="1139" alt="image" src="https://github.com/Shuffle/Shuffle/assets/25089558/45a7db1e-da7e-43c6-a1af-e36463c5dffc">


In Shuffle_Tools_1 it reference the Key "get_offense" and the Value "$get_offense.body", but no information is being passed bellow from the starting node "QRadar API" even though the information is there.


The objective is to get all the open offenses in QRadar and Create Alerts in TheHive5.
