### ISSUE TITLE
[Feature Request] Add raw extract from webhook requests

### ISSUE THREAD

**Issue by azgaviperr** [frikky/Shuffle#372]
It would be nice to have a raw extraction of the request received on a webhook for debug purposes. 
Could also be nice to be able to cache headers sent to it (Authent, labelling, ...) but this part is I think already requested.

**Comment by frikky** [comment]
I think what this will become instead is a way to failover to just showing the data as normal string if the data is "seemingly" valid json, but fails to parse.

**Comment by frikky** [comment]
Headers for auth are added. May indeed change it to handle data like in the http 1.3.0 app, but no plan to do so
