### ISSUE TITLE
Missing theme.js file in frontend subdirectory

### ISSUE THREAD

**Issue by gcallaghan** [frikky/Shuffle#375]
**Describe the bug**
The theme.js file appears to be missing from the front end sub directory

**To Reproduce**
Reading the code of App.jsx I see that theme is imported with a relative path to the same directory.
I do not see a theme.js or similar file
...

**Expected behavior**
I expect a theme.js file to be importable from that location

**Comment by frikky** [comment]
Hey, and thanks! 

I'm pretty much always working in the "Launch" branch, merging in new changes, and I honestly have no idea where the file went. I copied it over just now.
