### ISSUE TITLE
Frontend: Check if unsaved changes exist before starting the workflow

### ISSUE THREAD

**Issue by h0ng10** [frikky/Shuffle#39]
When starting a workflow, the frontend does currently not check if there are any unsaved changes. This might cause irritations, as the general expectation is that the currently displayed workflow gets executed.

Suggestion:
When pressing the play button, the frontend must check if the current workflow contains unsaved changes. In this case, the user should be asked if he wants to save the workflow before continuing, similar to a IDE...

It might also be great to have some kind of "auto-save" property, bound to the user and/or project.

**Comment by frikky** [comment]
I agree this is a feature that should be in. Probably both when you execute as well as try to exit. 

The latter part about auto-saving, do you think it should happen every time you change something? I guess this should be coupled with "test" workflows, AKA the ones you execute normally, and "production" workflows, to prevent overwriting one that e.g. has a schedule.

Thanks!

**Comment by h0ng10** [comment]
Regarding auto-saving, I would also be afraid of enabling this by default as you could easily destroy some existing workflows. Switching between development and production would be a good start.

**Comment by frikky** [comment]
Added a check that runs every time you try to leave in any way. There are a shitload of variables right now that might need checking if we only want it after a potential change, so I decided to not spend the time find all of them now

**Comment by frikky** [comment]
Keeping this open as it wasn't a proper fix, just a way to not potentially lose work.

**Comment by frikky** [comment]
This should now have sufficient checks once 00ff09a is pushed
