### ISSUE TITLE
Frontend: Argument field is not updated when switching between two nodes of the same type/action

### ISSUE THREAD

**Issue by h0ng10** [frikky/Shuffle#40]
## Description
I noticed that the argument field does not get updated if the user switches between to nodes that have the same type and action. It seems that the field is also not cleaned correctly

## Steps to reproduce:
- Create a testing node with the action "repeat back to me", name it testnode1, set the argument field to "test from testnode1"
- Create a second testing node with the same action ("repeat back to me"), name it testnode2, set the argument to "test from testnode2"
- Select testnode 1 again, notice that the text in arguments won't get updated.
- Add a third testing node, switch the action to "repeat back to me", notice that the argument field is already filled with the value from the previous selected node"

## Expected behaviour
The arguments field should display/contain the actual value from the currently selected node. If a new node is created, the argument field should be blank.

**Comment by frikky** [comment]
Was able to reproduce it, thanks!. Think it's got something to do with a specific React Hook not being reset, as you said. Will fix ASAP :)

Thanks!

**Comment by frikky** [comment]
They both wrote to the same memory location, because I didn't dereference it properly.. Added some other optimizations as well, so overall a good fix :)
