### ISSUE TITLE
Python library APP Creation

### ISSUE THREAD

**Issue by D4rkw0lv3s** [frikky/Shuffle#409]
**Describe the bug**
I was trying to create an Mysql/MariaDB App with some actions like:
- create/delete db
- create/delete table
- insert/update/delete table data
- search in mysql db

I was trying to use the mysql-connector-python, because it accepts json input so it would be easier to use the APP from the UI. Then I realized that the mysql-connector-python does not work with the docker image. I tried some work arounds but it did not worked.

**To Reproduce**
1. Create an app
2. add the mysql-connector-python to the requirements
3. in app.py import mysql-connector-python module
4. try to run it using the docker image
...

**Expected behavior**
To connect to mysql/mariadb by using this module

**Screenshots**

**Debug logs**
Run the following commands and paste them
```
docker logs shuffle-backend
docker ps -a
```

(if needed I can add the logs)

**Comment by frikky** [comment]
Thanks! Will have a look soon~

I am guessing it would just require the use of a different App SDK tho (as Alpine didn't work)

**Comment by D4rkw0lv3s** [comment]
Any update on this?

https://github.com/D4rkw0lv3s/Shuffle-apps/tree/mysql/mysql

**Comment by D4rkw0lv3s** [comment]
https://github.com/frikky/Shuffle-apps/pull/173

Resolved, switched to an old version of the library and it worked.
