### ISSUE TITLE
Replace NGINX with Caddy

### ISSUE THREAD

**Issue by h0ng10** [frikky/Shuffle#41]
The frontend is currently deployed via NGINX. I would suggest to use (Caddy)[https://caddyserver.com/] instead. 

While there is nothing wrong with NGINX, the usage of Caddy has several advantages, for example the automated generation of self signed certificates and out-of-the-box support for Let's encrypt.

I provide the changes as a pull request if you want..

**Comment by frikky** [comment]
This wouldn't initially help with a lot, so I won't prioritize it, but if you can make a pull request that works out of the box in a Docker container, I'm absolutely open to changing it.

Seems like it can take an Nginx config, so the potential migration shouldn't be too hard :)

**Comment by frikky** [comment]
Closing as we haven't seen any action here and I don't directly understand the benefits as it pertains to rolling out Shuffle
