### ISSUE TITLE
Backend crashes with panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by tesink** [frikky/Shuffle#414]
**Describe the bug**
Shuffle in Kubernetes cluster keeps restarting the backend pod due to a panic.

**Debug logs**
2021/06/14 19:31:13 Starting Shuffle backend - initializing database connection
2021/06/14 19:31:13 Finished Shuffle database init
2021/06/14 19:31:13 Starting INIT setup
2021/06/14 19:31:13 Running on shuffle-backend:5001
2021/06/14 19:31:13 Finalized init statistics update
2021/06/14 19:31:13 Organizations exist!
2021/06/14 19:31:13 There are 1 org(s).
2021/06/14 19:31:13 Should add 1 users to organization default
2021/06/14 19:31:13 [INFO] Username: admin, role: admin
2021/06/14 19:31:13 Setting up all environments with org a57043f1-5116-44d3-8991-6d9cf1cb8aed
2021/06/14 19:31:13 Setting up all app auths with org a57043f1-5116-44d3-8991-6d9cf1cb8aed
2021/06/14 19:31:13 Setting up all schedules with org a57043f1-5116-44d3-8991-6d9cf1cb8aed
2021/06/14 19:31:13 Starting cloud schedules for orgs!
2021/06/14 19:31:13 Skipping org a57043f1-5116-44d3-8991-6d9cf1cb8aed because sync isn't set (1).
2021/06/14 19:31:13 Relaunching schedules
2021/06/14 19:31:13 Setting up 0 schedule(s)
2021/06/14 19:31:13 Getting remote workflow apps
2021/06/14 19:31:16 [INFO] Setting 104 apps in cache for 10 minutes for workflowapps-sorted-500
2021/06/14 19:31:17 [INFO] Downloading OpenAPI data for search - EXTRA APPS
2021/06/14 19:31:18 [INFO] Finished git clone. Looking for updates to the repo.
2021/06/14 19:31:20 Added Wazuh OpenAPI:1.0.0 to the database from OpenAPI repo
2021/06/14 19:31:23 [INFO] Setting 105 apps in cache for 10 minutes for workflowapps-sorted-500
panic: assignment to entry in nil map

goroutine 13 [running]:
github.com/frikky/kin-openapi/openapi2conv.ToV3Parameter(0xc001c89058, 0xc0000b6d00, 0xc001deac20, 0x1, 0x1, 0xc001dea930, 0x1, 0x1, 0x0, 0x0)
	/go/pkg/mod/github.com/frikky/kin-openapi@v0.38.0/openapi2conv/openapi2_conv.go:236 +0xb95
github.com/frikky/kin-openapi/openapi2conv.ToV3Operation(0xc001c1b200, 0xc001c89058, 0xc001bc4620, 0xc001de4580, 0xc001deac20, 0x1, 0x1, 0xc001ddf0e0, 0x0, 0x0)
	/go/pkg/mod/github.com/frikky/kin-openapi@v0.38.0/openapi2conv/openapi2_conv.go:167 +0x265
github.com/frikky/kin-openapi/openapi2conv.ToV3PathItem(0xc001c1b200, 0xc001c89058, 0xc001bc4620, 0x0, 0x0, 0x0, 0xc001de4b00, 0x0, 0x0)
	/go/pkg/mod/github.com/frikky/kin-openapi@v0.38.0/openapi2conv/openapi2_conv.go:121 +0x19c
github.com/frikky/kin-openapi/openapi2conv.ToV3Swagger(0xc001c1b200, 0x6670, 0x6a80, 0xf29ea0)
	/go/pkg/mod/github.com/frikky/kin-openapi@v0.38.0/openapi2conv/openapi2_conv.go:69 +0x473
main.handleSwaggerValidation(0xc0019f9500, 0x6670, 0x6a80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20, 0xc001ad1980)
	/app/main.go:3936 +0x78a
main.iterateOpenApiGithub(0x11d2c68, 0xc002cd2660, 0xc00017a800, 0x48, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/app/walkoff.go:4352 +0x637
main.runInit(0x11c6760, 0xc00003c0a0)
	/app/main.go:5467 +0x1b5d
created by main.initHandlers
	/app/main.go:6074 +0x265

```
kubectl logs -n namespace shuffle-backend
```

**Comment by frikky** [comment]
Hey guys! Thanks for the report. We'll be upgrading the whole stack for everyone in about a week, with migration scripts and such - before then, we recommend using the "launch" branch of Shuffle. It has a lot of fixes (30+ versions released), and will become

Here's the install guide: https://github.com/frikky/Shuffle/blob/launch/.github/install-guide.md
Only edit before then; add "git checkout launch" to the end of step 2:

```
git clone https://github.com/frikky/Shuffle
cd Shuffle
git checkout launch
```

As it seems like you're using kubernetes here, please check the docker-compose https://github.com/frikky/Shuffle/blob/launch/docker-compose.yml and pick out the nightly versions, as well as migrating the database to Opensearch. We'll be providing a script for the migration soon.

**Comment by frikky** [comment]
Update: I made a hotfix for frikky/shuffle-backend_0.8.71 that fixes the crash as well

Please try it out if you don't want to update the entire stack yet :+1: 

```
docker pull frikky/shuffle-backend:0.8.71
```

**Comment by tesink** [comment]
Yes, that solved the issue. Thanks for hotfixing it in 0.8.71 as well, and your great work with Shuffle!
