### ISSUE TITLE
Arguments/Parameters within a self-created app cannot be set

### ISSUE THREAD

**Issue by timoles** [frikky/Shuffle#43]
I tried creating an App "From Scratch" and within the `Action` i had a variable within the URL. (see `{test2}`)

![parameter_wrong_1](https://user-images.githubusercontent.com/18122064/83639337-13906c00-a59a-11ea-9be5-e3d62c62b5ca.png)

When the App is implemented into a `Workflow` the frontend does not provide a way to set the "path" variable. 

![parameter_wrong_3](https://user-images.githubusercontent.com/18122064/83639501-4a668200-a59a-11ea-9e87-c869a5273b78.png)

When executing the Workflow the application throws an error due to the missing path variable

![parameter_wrong_2](https://user-images.githubusercontent.com/18122064/83639556-5eaa7f00-a59a-11ea-8de6-44e679ae0110.png)

I tried checking out how/where the app resolves the arguments/parameters, but couldn't really find the correct code snippet. All I could find was the parameter setting [here](https://github.com/frikky/Shuffle/blob/b9b3cd2e71a3f0a904814e612d4f3dc3de758885/frontend/src/AngularWorkflow.js#L2198), but I couldn't find the backend code which is responsible for serving the parameters.

**Comment by frikky** [comment]
This was a frontend issue where the URL path in the action was being reset before the action was submitted. 

Code generation is kind of messy, so finding the exact place where something goes wrong might be tricky. I appreciate the help :green_heart:

**Comment by timoles** [comment]
Thank you very much for the quick fix. Also thanks for the logging change in the go code, now I have an lead were to check for these things within the backend.
