### ISSUE TITLE
Check if App is in use before allowing App deletion 

### ISSUE THREAD

**Issue by timoles** [frikky/Shuffle#44]
It is currently possible to delete an existing app, even if it is used within a workflow. 
It could be a nice usability feature to check if the app is currently in use, before a user is allowed to delete it. This would make it harder for a user to silently break existing workflows.

**Comment by frikky** [comment]
Thanks!

This is a vital feature that I've just stayed away from fixing because of more pressing issues. I'm thinking it will be something like this:
1. Try to delete it
2. Popup with yes/no to delete, which includes the workflows it's currently used in
3. If deleted, triggers are stopped and error is set to True for them.

**Comment by frikky** [comment]
Didn't add the option to see which workflows when deleting, but I set the workflows AND actions to have errors, which means they need manual fixing.

Delete verification:
![image](https://user-images.githubusercontent.com/5719530/83714373-db853980-a62a-11ea-8c30-86808e0a124c.png)

Invalid workflow:
![image](https://user-images.githubusercontent.com/5719530/83714421-fa83cb80-a62a-11ea-91af-92a85270bb22.png)

Invalid Action in Workflow:
![image](https://user-images.githubusercontent.com/5719530/83714445-10918c00-a62b-11ea-926c-9a324f746ccb.png)

Currently it forces you to remake actions that have errors. Errors can be seen by clicking the node as usual, but that won't work if the app doesn't exist, so remaking the node/action is the only option.

**Comment by frikky** [comment]
Removed bug tag, as the workflow lookup addition is just an enhancement. Pushed build to prod, so it's ready to be updated.
