### ISSUE TITLE
webapp binary in the "backend" directory

### ISSUE THREAD

**Issue by timoles** [frikky/Shuffle#45]
Within the "backend->app" directory [here](https://github.com/frikky/Shuffle/tree/master/backend/go-app) the compiled webapp is present. I'm not sure if this is intentional, or this was an oversight. 
If its intentional it would probably a good idea to compile the webapp during the Docker build process.

Also within the directory is a readme which probably belongs to the "backend" database development setup, as it "describes" the gcloud database setup.

**Comment by frikky** [comment]
This was originally because of issues while building inside the Dockerfile, which was later fixed here: https://github.com/frikky/Shuffle/blob/master/backend/Dockerfile#L21

Removed the README as well, as it has no use anymore.

**Comment by ale9878** [comment]
#ciao

**Comment by ale9878** [comment]
Ciao #

>

**Comment by ale9878** [comment]
Ciso

**Comment by frikky** [comment]
Hey @ale9878, whatsup? :partying_face:

**Comment by ale9878** [comment]
Mollami

**Comment by ale9878** [comment]
E finita nn mi cercare piu

Il Ven 19 Giu 2020, 05:54 Frikky <notifications@github.com> ha scritto:

**Comment by ale9878** [comment]
🖕🖕🖕🖕🖕
