### ISSUE TITLE
Save app failed - Internet required for App Builder

### ISSUE THREAD

**Issue by heng-zhang-20** [frikky/Shuffle#451]
**Describe the bug**

When saving Shuffle App from scratch, message shows like this:

`Error: Error in Docker build: Failed building frikky/shuffle:xxx,frikky/shuffle:app_1.0.0. Check backend logs for details. Most likely means you have an old version of Docker.`

But my Docker version is latest: Docker version 20.10.7, build f0df350 .

**Expected behavior**

Save app successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/67679070/127272005-8cf0dd0c-acba-43d9-a89c-979b369faed2.png)

**Backend Debug logs**

ERROR ABOVE: Trying to pull tags from: frikky/shuffle:xxx
frikky/shuffle:pafw_1.0.0
2021/07/28 05:50:06 [ERROR] Docker build error: Failed building frikky/shuffle:xxx,frikky/shuffle:app_1.0.0. Check backend logs for details. Most likely means you have an old version of Docker.

**Comment by frikky** [comment]
Can you click the "Save" button again and send more logs from around the same time it's clicked? Run this before clicking :)

```
docker logs -f shuffle-backend
```

Thanks!

**Comment by heng-zhang-20** [comment]
**Backend Debug logs after clicking SAVE button**
2021/07/28 05:48:07 [INFO] Successfully parsed APP-name-d4997d7aa1b69452073f4bc4b867f167. Proceeding to docker container
2021/07/28 05:48:07 [INFO] Added APP-name:1.0.0 to the database
2021/07/28 05:48:07 [INFO] Successfully stitched ZIPFILE for APP-name-d4997d7aa1b69452073f4bc4b867f167
2021/07/28 05:48:07 [INFO] Dockerfile: generated/APP-name-d4997d7aa1b69452073f4bc4b867f167/Dockerfile
2021/07/28 05:48:07 [INFO] Docker Tags: [frikky/shuffle:APP-name-d4997d7aa1b69452073f4bc4b867f167 frikky/shuffle:app-name_1.0.0]
2021/07/28 05:50:06 [ERROR] Docker build:
{"stream":"Step 1/13 : FROM frikky/shuffle:app_sdk as base"}
{"stream":"\n"}
{"stream":" ---\u003e c3f01d29f256\n"}
{"aux":{"ID":"sha256:c3f01d29f256bd2c724369847d0f282adc1cdd66ccb42cda3b78cb1cde14881a"}}
{"stream":"Step 2/13 : FROM base as builder"}
{"stream":"\n"}
{"stream":" ---\u003e c3f01d29f256\n"}
{"stream":"Step 3/13 : RUN apk --no-cache add --update alpine-sdk libffi libffi-dev musl-dev openssl-dev"}
{"stream":"\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 20ef32259154\n"}
{"stream":"Step 4/13 : RUN mkdir /install"}
{"stream":"\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 40c1bff16c8d\n"}
{"stream":"Step 5/13 : WORKDIR /install"}
{"stream":"\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 9e1d023386f6\n"}
{"stream":"Step 6/13 : COPY requirements.txt /requirements.txt"}
{"stream":"\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e ad6409f5d709\n"}
{"stream":"Step 7/13 : RUN pip install --prefix=\"/install\" -r /requirements.txt"}
{"stream":"\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 440d46597360\n"}
{"aux":{"ID":"sha256:440d46597360e0b4ee9a129ec01ec24e767cc187224df4d305339444de086c42"}}
{"stream":"Step 8/13 : FROM base"}
{"stream":"\n"}
{"stream":" ---\u003e c3f01d29f256\n"}
{"stream":"Step 9/13 : COPY --from=builder /install /usr/local"}
{"stream":"\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 1f42f9338808\n"}
{"stream":"Step 10/13 : COPY src /app"}
{"stream":"\n"}
{"stream":" ---\u003e 5b0108321618\n"}
{"stream":"Step 11/13 : RUN apk --no-cache add --update libmagic"}
{"stream":"\n"}
{"stream":" ---\u003e Running in e16960702fc1\n"}
{"stream":"fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz\n"}
{"stream":"fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz\n"}
{"stream":"\u001b[91mWARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: Permission denied\n\u001b[0m"}
{"stream":"\u001b[91mERROR: unable to select packages:\n\u001b[0m"}
{"stream":"  libmagic (no such package):\n    required by: world[libmagic]\n"}
{"errorDetail":{"code":1,"message":"The command '/bin/sh -c apk --no-cache add --update libmagic' returned a non-zero code: 1"},"error":"The command '/bin/sh -c apk --no-cache add --update libmagic' returned a non-zero code: 1"}

ERROR ABOVE: Trying to pull tags from: frikky/shuffle:APP-name-d4997d7aa1b69452073f4bc4b867f167
frikky/shuffle:pafw_1.0.0
2021/07/28 05:50:06 [ERROR] Docker build error: Failed building frikky/shuffle:APP-name-d4997d7aa1b69452073f4bc4b867f167,frikky/shuffle:app-name_1.0.0. Check backend logs for details. Most likely means you have an old version of Docker.

**Comment by frikky** [comment]
Thanks! That's an error we should be sending to the frontend to help you understand what went wrong. 

It's a Docker error, coming from the fact that you didn't have access to download the Alpinelinux packages remotely, or they don't exist.

**Comment by heng-zhang-20** [comment]
Shuffle server can connect to internet. I think poor network is a major cause of this error. Thanks for resolving. You can close this issue.

**Comment by frikky** [comment]
> Shuffle server can connect to internet. I think poor network is a major cause of this error. Thanks for resolving. You can close this issue.

I wonder if there's a way to solve this for normal packages though :thinking: 

As this is OpenAPI and standardized, there's no real reason it should have to download anything, as it could be included in the App SDK :octocat:

**Comment by frikky** [comment]
Migrated this into an enhancement instead of closing :+1:

**Comment by heng-zhang-20** [comment]
I created app from SCRATCH not OPENAPI. Why did Shuffle try to download apkindex? I think you can answer this question as an author. 

I'll do what I can do for solving this problem if needed.

**Comment by frikky** [comment]
> I created app from SCRATCH not OPENAPI. Why did Shuffle try to download apkindex? I think you can answer this question as an author.
> 
> I'll do what I can do for solving this problem if needed.

When using the App editor it always builds OpenAPI behind the scenes to make the apps share-able, so those options are kind of identical. In the background it's still running a Docker build with Dockerfile (etc), which may be downloading too much.

Can you check if you have access to this from the server?

https://dl-cdn.alpinelinux.org/alpine/v3.13/main

**Comment by heng-zhang-20** [comment]
This is twice ping result to dl-cdn.alpinelinux.org, terrible network.

```
# ping dl-cdn.alpinelinux.org -c 10
PING dualstack.d.sni.global.fastly.net (151.101.230.133) 56(84) bytes of data.
64 bytes from 151.101.230.133 (151.101.230.133): icmp_seq=1 ttl=52 time=67.9 ms
64 bytes from 151.101.230.133 (151.101.230.133): icmp_seq=2 ttl=52 time=68.1 ms
64 bytes from 151.101.230.133 (151.101.230.133): icmp_seq=3 ttl=52 time=70.6 ms
64 bytes from 151.101.230.133 (151.101.230.133): icmp_seq=4 ttl=52 time=67.1 ms
64 bytes from 151.101.230.133 (151.101.230.133): icmp_seq=6 ttl=52 time=69.9 ms
64 bytes from 151.101.230.133 (151.101.230.133): icmp_seq=7 ttl=52 time=69.2 ms
64 bytes from 151.101.230.133 (151.101.230.133): icmp_seq=8 ttl=52 time=67.8 ms
64 bytes from 151.101.230.133 (151.101.230.133): icmp_seq=10 ttl=52 time=68.4 ms

--- dualstack.d.sni.global.fastly.net ping statistics ---
10 packets transmitted, 8 received, 20% packet loss, time 9009ms
rtt min/avg/max/mdev = 67.118/68.659/70.678/1.138 ms

# ping dl-cdn.alpinelinux.org
PING dualstack.d.sni.global.fastly.net (151.101.110.133) 56(84) bytes of data.
64 bytes from 151.101.110.133 (151.101.110.133): icmp_seq=23 ttl=51 time=69.9 ms
64 bytes from 151.101.110.133 (151.101.110.133): icmp_seq=24 ttl=51 time=69.8 ms
...
^C
--- dualstack.d.sni.global.fastly.net ping statistics ---
53 packets transmitted, 31 received, 41% packet loss, time 52028ms
rtt min/avg/max/mdev = 61.612/68.568/75.857/2.198 ms
```

**Comment by frikky** [comment]
Looks like we may need a proper fix - this won't be a quick one tho, as it's a major change to the build environment used everywhere

**Comment by frikky** [comment]
Should be fixed with the new App SDK, which has everything already included for this.
