### ISSUE TITLE
CORS misconfiguration for API server

### ISSUE THREAD

**Issue by timoles** [frikky/Shuffle#46]
The `webapp` backend is most likely misshandling CORS requests. 
[This code snippet](https://github.com/frikky/Shuffle/blob/b9b3cd2e71a3f0a904814e612d4f3dc3de758885/backend/go-app/main.go#L2167) sets the `Access-Control-Allow-Origin` response Header to whatever value the `Origin` Request header is set. 

This behaviour allows for potential [CORS-based attacks](https://portswigger.net/web-security/cors).
Instead of simply reflecting the request `Origin` header, a CORS whitelist with trusted sites should be created. 

Example Request (The Header value:  `attacker-controlled-value` is reflected within the response)

```
GET /api/v1/apps HTTP/1.1
Host: localhost:3443
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json
Connection: close
Origin: attacker-controlled-value
```

**Comment by frikky** [comment]
Thanks, I totally forgot about this one (it's been there since I started the project)!

I guess all the headers being set should be inside the "OPTIONS" if check itself. No changes to this should reflect production builds anyway.

**Comment by frikky** [comment]
Pushed the fix to master and latest Dockerhub image :heart:
