### ISSUE TITLE
Allow custom authentication in App creator

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#474]
Allow e.g. to run custom python code that generates the necessary data

Example app which requires it:
- AWS (all of them)
- Darktrace (https://shuffler.io/apps/f9a3b4deb7e1f270fbb8fda5c591e3c3)

**Comment by pemontto** [comment]
Does this also apply to Azure with the [oauth2 client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) or is that handled differently now?

**Comment by frikky** [comment]
> Does this also apply to Azure with the [oauth2 client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) or is that handled differently now?

We don't have Oauth2 with client creds yet, but it's on our todo, as we're looking to leverage delegated API's more and more. This issue is more for custom credentials that don't required redirects and such. Oauth2 will be a standard thing you can just specify if it's done right. 

Largest issue with oauth2 onprem will probably be redirect URL's :thinking: 

I'm gonna prototype it this weekend I think.

**Comment by frikky** [comment]
Closing as we probably won't make custom auth anytime soon, as that would eb a custom App

#168 for Oauth2 info
