### ISSUE TITLE
Doubt this is a bug but error when running "docker-compose up -d"

### ISSUE THREAD

**Issue by pcyr44** [frikky/Shuffle#49]
After cloning from Github I ran the docker-compose command and I am getting a certificate error while attempting to build backend:

go: cloud.google.com/go@v0.57.0: Get "https://proxy.golang.org/cloud.google.com/go/@v/v0.57.0.mod": x509: certificate signed by unknown authority
ERROR: Service 'backend' failed to build: The command '/bin/sh -c go get -v' returned a non-zero code: 1

I have updated ca-certiifcates and no luck, is there a location in you image where I can excluded SSL validation for go?

**Comment by frikky** [comment]
Hey @pcyr44. Assuming you cloned for the first time yesterday, this was my mistake. I pushed a bad docker-compose to master which made you create the image yourself rather than pull it from Dockerhub.

Could you run the following? 
```
git pull
docker-compose down
docker-compose pull
docker-compose up -d
```

**Comment by pcyr44** [comment]
Works perfect, thanks for the quick response.
