### ISSUE TITLE
Can't change my password as a non-admin

### ISSUE THREAD

**Issue by gc-advens** [frikky/Shuffle#490]
**Describe the bug**
When trying to change my password as a non-admin user, I get an error "Username and/or password is incorrect" even if both are correct.

**To Reproduce**
1. As a non-admin user, visit /settings
2. Fill-in the correct current password, and a valid, different new password
3. Click on 'Submit password change'

**Expected behavior**
The password is successfully changed, no error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/82955277/130965705-86b40451-0644-446c-b845-38a7985c6b36.png)

**Debug logs**
I don't have access to the logs, but the admin told me that they contain this error
```
crypto/bcrypt: hashedPassword is not the hash of the given password
```

---

From reading the code, it seems to me that the database password is compared with the *new* password instead of the *current* one:
```go
if userInfo.Role != "admin" {
	err = bcrypt.CompareHashAndPassword([]byte(userInfo.Password), []byte(t.Newpassword))
	if err != nil {
		log.Printf("Bad password for %s: %s", userInfo.Username, err)
		resp.WriteHeader(401)
		resp.Write([]byte(`{"success": false, "reason": "Username and/or password is incorrect"}`))
		return
	}
}
```
https://github.com/frikky/shuffle-shared/blob/289005330a9b613407cc1e3c2fde6d280b59be81/shared.go#L3630-L3638

**Comment by frikky** [comment]
You were correct! It's been fixed and a part of the next nightly
