### ISSUE TITLE
Must rely on Google cloud?

### ISSUE THREAD

**Issue by 219liangyi** [frikky/Shuffle#494]
This project must be deployed in Google cloud? Can't the company privatize intranet deployment?

**Comment by frikky** [comment]
> This project must be deployed in Google cloud? Can't the company privatize intranet deployment?

Hey - this does not have anything to do with any Google cloud projects anymore at all! It's always been possible to deploy locally without any external reference - the last piece was to fix the database, which is now changed to Opensearch (Elasticsearch). 

Feel free to deploy it as you wish in your private intranet :+1:

**Comment by frikky** [comment]
Closing as no more activity. Feel free to reopen @219liangyi :)
