### ISSUE TITLE
Docker app sdk and worker exits unexpectedly

### ISSUE THREAD

**Issue by kp625544** [frikky/Shuffle#5]
Hello,
I tried starting shuffle with the docker command and the images stop unexpectedly because of which I m getting 502 error while doing the admin setup it seems.
![Screenshot 2020-05-21 at 1 52 09 PM](https://user-images.githubusercontent.com/18206620/82539160-982ac580-9b6a-11ea-836c-73c9bcc5db09.png)
![Screenshot 2020-05-21 at 1 56 10 PM](https://user-images.githubusercontent.com/18206620/82539311-e049e800-9b6a-11ea-8cd8-d858b3f78f40.png)

**Comment by frikky** [comment]
Seems to be forwarding issue in the backend. The app_sdk and worker exits are working as expected.

Remaking the Docker-compose with Dockerhub to eliminate possible build issues :+1:

**Comment by cudeso** [comment]
This is what's in docker logs for the nginx container (frontend)

```
2020/05/21 09:06:36 [emerg] 1#1: host not found in upstream "shuffle-backend" in /etc/nginx/nginx.conf:52
nginx: [emerg] host not found in upstream "shuffle-backend" in /etc/nginx/nginx.conf:52
```

**Comment by frikky** [comment]
Thanks! Dependency order in the docker-compose indicates that the backend needs the frontend, not the other way around. There's also an nginx config issue..

**Comment by frikky** [comment]
> Thanks! Dependency order in the docker-compose indicates that the backend needs the frontend, not the other way around. There's also an nginx config issue..

Another issue with the first webserver init. Working on a fix to make it come up instantly!

**Comment by frikky** [comment]
Can you try to pull, and rerun docker-compose up?

It should pull from Dockerhub rather than a local build.
It seems way faster, so this was good change.

**Comment by kp625544** [comment]
Now its trying to make request on 192.168.3.6:5001
![Screenshot 2020-05-21 at 3 46 35 PM](https://user-images.githubusercontent.com/18206620/82549333-6883b980-9b7a-11ea-9a64-eb0c1372a773.png)

**Comment by cudeso** [comment]
Seems to be OK now.
Also did a `sudo docker-compose up -d --force-recreate`

<img width="1489" alt="Shuffle_-_Apps" src="https://user-images.githubusercontent.com/256028/82550473-dcb06400-9b5e-11ea-9eb2-51ca93b45752.png">

**Comment by kp625544** [comment]
> Seems to be OK now.
> Also did a `sudo docker-compose up -d --force-recreate`
> 
> <img alt="Shuffle_-_Apps" width="1489" src="https://user-images.githubusercontent.com/256028/82550473-dcb06400-9b5e-11ea-9eb2-51ca93b45752.png">

@cudeso did you try it on a gcp server? my requests are still going to 192.168.3.6:5001 even after a reinstallation from scratch on a new server

**Comment by cudeso** [comment]
> > Seems to be OK now.
> > Also did a `sudo docker-compose up -d --force-recreate`
> > <img alt="Shuffle_-_Apps" width="1489" src="https://user-images.githubusercontent.com/256028/82550473-dcb06400-9b5e-11ea-9eb2-51ca93b45752.png">
> 
> @cudeso did you try it on a gcp server? my requests are still going to 192.168.3.6:5001 even after a reinstallation from scratch on a new server

No, was not on GCP.

**Comment by frikky** [comment]
Hey guys, do you mind running ```sudo docker-compose up -d --force-recreate``` again to test?

I've updated the frontend Docker image, and it hopefully doesn't correspond to my local environment now :P

**Comment by kp625544** [comment]
Still its making request to 192.168.3.6. I see this IP hardcoded in some of the files:

- frontend/src/App.js:41://const globalUrl = "http://192.168.3.6:5001"
- backend/run.sh:14:	--env DATASTORE_EMULATOR_HOST=192.168.3.6:8000
- backend/tests/forparser.py:4
- backend/webhook/run.sh:9: -e "CALLBACKURL=http://192.168.3.6:5001/api/v1/hooks/d6ef8912e8bd37776e654cbc14c2629c/result"

**Comment by frikky** [comment]
Hey! 

The request goes to 192.168.3.6, because that's what WAS (in the past) the IP in the frontend docker container (frikky/shuffle:frontend). 

Run this to get the latest :)
```
docker-compose pull
docker-compose up
```

**Comment by kp625544** [comment]
worked. perfect!
