### ISSUE TITLE
When attempting to download apps from frikky github getting an error

### ISSUE THREAD

**Issue by pcyr44** [frikky/Shuffle#50]
when attempting to clone apps within the GUI from https://github.com/frikky/shuffle-apps, I am getting an error:

SYNTAXERROR: 
JSON.PARSE:
EXPECTED ',' OR '}'
AFTER PROPERTY 
VALUE IN OBJECT AT
LINE 1 COLUMN 36 OF
THE JSON DATA

![image](https://user-images.githubusercontent.com/54074548/83876878-8d923380-a707-11ea-9b5d-f5765b5eb66a.png)

Thanks for your help again.

**Comment by frikky** [comment]
Bump @pcyr44  :)

**Comment by pcyr44** [comment]
Sorry, you can close it. It is on my side, SSL inspection breaking it. Thanks.

**Comment by frikky** [comment]
Glad you got it fixed!
