### ISSUE TITLE
[FR] Workflow Group Organisation (Use Case Integration)

### ISSUE THREAD

**Issue by D4rkw0lv3s** [frikky/Shuffle#511]
**Is your feature request related to a problem? Please describe.**
Easily group workflows by "use case integration", like group all workflows that contribute to the integration between QRadar and Thehive for example, or group all workflows that automate TheHive only. This way we could easily see which workflows are related to that use case integration.

**Describe the solution you'd like**
My suggestion would be to add a group system where you can inside the home page use a filter to select the group/s. Maybe allow a workflow to be part of multiple groups, in order to allow the user to be "free" when organizing/categorizing the workflows.

**Describe alternatives you've considered**
-> Will let this open in case of suggestion in the comments section.

**Additional context**
...

**Comment by frikky** [comment]
I think grouping by usecase category or something will be the way we go with this. The new /usecases UI will be merged with /workflows to help make this simpler, and sortable
