### ISSUE TITLE
Apps

### ISSUE THREAD

**Issue by Faceless28** [frikky/Shuffle#515]
While shuffle have 117 installed apps i've only being able to use few of them in workflows
Shuffle-0.9.0
other version have same bug.

**Comment by frikky** [comment]
> While shuffle have 117 installed apps i've only being able to use few of them in workflows
> Shuffle-0.9.0
> other version have same bug.

Hey!

What exactly is the bug you're facing? What are you trying to do?

Thanks!

**Comment by frikky** [comment]
Closing because of lack of a response - please reopen if you have an update :)
