### ISSUE TITLE
Local development installation report errors

### ISSUE THREAD

**Issue by 219liangyi** [frikky/Shuffle#516]
**Describe the bug**

export SHUFFLE_OPENSEARCH_URL="http://localhost:9200"
cd backend/go-app
go run *.go

Hello, I want to deploy the project locally for development, but I always remind me to connect to Google could. I still remind me after commenting some. I want to use opensearch deployment locally to start and participate in the development. thank you

** Debug logs **
bug one:
go: downloading github.com/frikky/shuffle-shared v0.0.93
2021/09/14 16:51:33 [DEBUG] Starting Shuffle backend - initializing database connection
2021/09/14 16:51:33 [DEBUG] Database client error during init: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

bug two:
2021/09/14 17:51:21 [DEBUG] Getting organizations
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x16ead09]

goroutine 13 [running]:
cloud.google.com/go/datastore.(*Iterator).nextBatch(0xc000112090, 0xc00059e120, 0x0)
        /Applications/xiaotudou/go/pkg/mod/cloud.google.com/go/datastore@v1.4.0/query.go:692 +0xd9
cloud.google.com/go/datastore.(*Iterator).next(0xc000112090, 0x27017a0, 0xc000730030, 0xc0007261d8, 0xc000112090)
        /Applications/xiaotudou/go/pkg/mod/cloud.google.com/go/datastore@v1.4.0/query.go:647 +0x43
cloud.google.com/go/datastore.(*Client).GetAll(0x33ea550, 0x2701720, 0xc000044060, 0xc0007261d8, 0x2052800, 0xc00072a000, 0x0, 0x0, 0x0, 0x0, ...)
        /Applications/xiaotudou/go/pkg/mod/cloud.google.com/go/datastore@v1.4.0/query.go:521 +0x18e
github.com/frikky/shuffle-shared.GetAllOrgs(0x2701720, 0xc000044060, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Applications/xiaotudou/go/pkg/mod/github.com/frikky/shuffle-shared@v0.0.93/db-connector.go:4120 +0x17f
main.runInitEs(0x2701720, 0xc000044060)
        /Users/xiaotudou/okObject/Shuffle/backend/go-app/main.go:3892 +0x14e
created by main.initHandlers
        /Users/xiaotudou/okObject/Shuffle/backend/go-app/main.go:5734 +0x38dc

```
thanks
```

**Comment by frikky** [comment]
The documentation isn't entirely completed; please check out this updated one and tell us if it works or not: https://github.com/frikky/Shuffle/blob/launch/.github/install-guide.md#backend---golang

Thanks!

**Comment by frikky** [comment]
Hey! Did you get this sorted out?

**Comment by 219liangyi** [comment]
Thank you. This problem has been solved. However, I found that my problem is that the program cannot read the. env configuration file. My system is Mac OS 11.4
in main.go
import _ "github.com/joho/godotenv/autoload"
err := godotenv.Load("../../.env")
if err != nil {
   log.Fatalf("Error loading .env file")
}
success !!
