### ISSUE TITLE
.env not respecting docker-compose.yml

### ISSUE THREAD

**Issue by idev** [frikky/Shuffle#52]
**Describe the bug**
At MacOS the docker is not starting because of: 
ERROR: for database  Cannot start service database: Mounts denied: 
The path /etc/shuffle
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.

Try to change File Sharing preferences as described in docker-compose.yml, but still got the error. Finally updating the .env file to the same location works.

**Comment by frikky** [comment]
Hey @idev! I'm not sure if I follow exactly as I think you've got it the other way around:
docker-compose.yml uses data from .env, not .env from docker-compose.

This means that you can change the DB_LOCATION variable in .env to a valid path on OS X, and it should work :+1: 
I'll make sure to document this, and migrate the location to somewhere else in a later build.

**Comment by idev** [comment]
Ok, sorry - i justed googled the error, and the solution was to change it in docker-compose.yml.
Can be closed!
