### ISSUE TITLE
How do I configure the HTTP Trigger hostname? (or the shuffle console hostname)

### ISSUE THREAD

**Issue by Jeff-Lowrey** [frikky/Shuffle#527]
I can't find any information on how to change the hostname in HTTP Trigger URLs so that they are not "https://localhost".

I need to set this to a different hostname value. 

How or where would change this? In the frontend ngix configuration?

**Comment by frikky** [comment]
> I can't find any information on how to change the hostname in HTTP Trigger URLs so that they are not "https://localhost".
> 
> I need to set this to a different hostname value.
> 
> How or where would change this? In the frontend ngix configuration?

Hey! Do you mean the Webhook trigger?

This just defaults to showing the URL you're using in the URL bar. if you're e.g. visiting Shuffle on http://localhost:3001, then it's going to use http://localhost:3001/api/v1/... Visit the page using your machine's hostname/IP and it should change automatically. 

PS: This is exactly why we made Shuffle Hybrid. If you want a public URL for your workflow (https://shuffler.io...) for your on-premises executions, send me an email frikky@shuffler.io and reference this issue :+1:

**Comment by Jeff-Lowrey** [comment]
Hi -
Yes, I did mean the webhook trigger.  And i do see that if I log in using a different address, it does change.

Thank you!
