### ISSUE TITLE
Shuffle-database failing to build

### ISSUE THREAD

**Issue by rnolen-stripe** [frikky/Shuffle#53]
**Describe the bug**
I am looking to test some functionalities of Shuffle and I went to setup the docker environment on my OSX machine and have been running into issues getting Shuffle up

OSX: 10.15.5
Docker Engine:19.03.8
Compose: 1.25.5 

I have added the proper mount places to docker under File Sharing(since it is an OSX host). 

I am continuing to work through the issue, but figured since this is new and getting under way I would communicate

```
docker-compose up
Creating network "shuffle_shuffle" with driver "bridge"
Creating shuffle-orborus  ... error
Creating shuffle-database ...

Creating shuffle-database ... error

ERROR: for shuffle-database  Cannot start service database: Mounts denied: EOF

ERROR: for orborus  Cannot start service orborus: Mounts denied: EOF

ERROR: for database  Cannot start service database: Mounts denied: EOF
ERROR: Encountered errors while bringing up the project.
st-rnolen1:Shuffle rnolen$ docker-compose up
Starting shuffle-database ...
Starting shuffle-orborus  ...

ERROR: for shuffle-orborus  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for shuffle-database  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for orborus  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for database  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```
Debug 
```
docker logs shuffle-backend
Error: No such container: shuffle-backend


docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                         PORTS                                                                                   NAMES
426940011c91        frikky/shuffle:database        "gcloud beta emulato…"   16 minutes ago      Created                                                                                                                shuffle-database
504f685af6bb        frikky/shuffle:orborus         "./orborus"              16 minutes ago      Created                                                                                                                shuffle-orborus
```

**Comment by frikky** [comment]
Haven't seen this one before, but it seems like it can't get a port for any of the services, or its just timing out. With a quick search I found [this](https://github.com/docker/compose/issues/3927#issuecomment-245948736):

```
export DOCKER_CLIENT_TIMEOUT=120
export COMPOSE_HTTP_TIMEOUT=120
```

**Other solutions people mentioned in this thread:**
Restart Docker (try this one)
Increase Docker CPU & memory


Please tell me if that works! :partying_face:

**Comment by frikky** [comment]
@rnolen-stripe boop :)

**Comment by rnolen-stripe** [comment]
@frikky was able to get it all squared away. It was a combination between the `.env` file (where the code sources the database mount path) and just some slow build on my side. I have a change to the `.env` file for compatibility to OSX or run the `docker-compose up -d` with privs. Will reach out to you over discussion on the approach for the fix.

**Comment by frikky** [comment]
As I wrote in our email conversation - I changed the default database location to ./shuffle-database rather than /etc/shuffle. This is to prevent locations outside of the current directory, as well as software-specific bugs related to e.g. OS X.
