### ISSUE TITLE
[BUG] Troubleshoot import of workflow - Subflow keeps old API Key attribute

### ISSUE THREAD

**Issue by azgaviperr** [frikky/Shuffle#546]
**Describe the bug**
Using the troubleshoot script to export and import workflow into a new instance works and keep track of info like webhook path and such. However in the case of Subflow nodes, the old API is passed to the workflow an therefore need to be recreated to  work after import.

**Comment by frikky** [comment]
Properly fixed now. Subflows no longer saves the apikey at all, and will instead use the authorization key of its parent.

Fixed in 0.9.42
