### ISSUE TITLE
Hello, what is this flag used for and what is its specific function

### ISSUE THREAD

**Issue by 219liangyi** [frikky/Shuffle#579]
![image](https://user-images.githubusercontent.com/19781251/142633236-b122c176-1bed-4f1e-ab1b-1de47cf1c547.png)
After clicking, the icon turns into a circle. Is there any introduction to this function? thank you

**Comment by frikky** [comment]
> ![image](https://user-images.githubusercontent.com/19781251/142633236-b122c176-1bed-4f1e-ab1b-1de47cf1c547.png) After clicking, the icon turns into a circle. Is there any introduction to this function? thank you

This sets the startnode! That means all executions will start on that node.

Here's a new issue for the documentation of it: https://github.com/Shuffle/Shuffle-docs/issues/58

Thanks!
