### ISSUE TITLE
[Bug] Ctrl + C then Ctrl + V copies elements

### ISSUE THREAD

**Issue by DavidtheGoliath** [frikky/Shuffle#581]
**Ctrl + C then Ctrl + V copies elements**
As stated Ctrl + C then Ctrl + V copies elements and not the text say the API key for

**To Reproduce see attached video**

https://user-images.githubusercontent.com/31187099/142837061-24300841-2040-4a66-b3b8-9119652c565f.mp4

**Comment by frikky** [comment]
Fixed in latest versions! Problem was with not unmounting CTRL+C parser when going from a workflow view.
