### ISSUE TITLE
[BUG] Deleting a scheduler in a workflow don't stop it

### ISSUE THREAD

**Issue by azgaviperr** [frikky/Shuffle#588]
If a scheduler is deleted with clicking on stop on the workflow first doesn't delete it from the schedule tab in admin. 

Because of that the scheduler is still active but not possible to see it in the workflow (potential brain dommage on the operator)

Exemple: Schedule deleted the day before on the workflow 

![image](https://user-images.githubusercontent.com/7451354/143432797-e92dcded-6ed5-4ab5-8e6b-242ca5527ecb.png)

But still present there: 

![image](https://user-images.githubusercontent.com/7451354/143432913-c4cde92f-2ddd-4629-8317-7ae7808cdf58.png)

**Comment by frikky** [comment]
Thanks!

**Comment by frikky** [comment]
This was fixed some time back :)
