### ISSUE TITLE
https://discord.gg/B2CBzUm What is it?

### ISSUE THREAD

**Issue by 219liangyi** [frikky/Shuffle#589]
![image](https://user-images.githubusercontent.com/19781251/143568605-e611ca5f-c3cf-4aa0-ae55-d2bb5fc7fba2.png)
Where does this button link jump to? It should jump to docs

**Comment by 219liangyi** [comment]
![image](https://user-images.githubusercontent.com/19781251/143568859-d9bc6f82-e686-402b-932a-602b42f48164.png)

**Comment by frikky** [comment]
The point of the text is to show where you can get help for apps in general. 

Discord is our support, forum and community platform, and linking to it is better than linking to nothing. Over time, we'll fill it all up with proper documentation, but we got enough help for that, this is the best we can do. 

We're open to suggestions! :)
