### ISSUE TITLE
Error while installing packages on ubuntu server

### ISSUE THREAD

**Issue by kp625544** [frikky/Shuffle#6]
While running `sudo apt -y update && sudo apt -y upgrade && sudo apt install -y google-cloud-sdk-app-engine-python google-cloud-sdk-app-engine-python google-cloud-sdk-datastore-emulator google-cloud-sdk-app-engine-go` it gives the following error:

> E: Unable to locate package google-cloud-sdk-app-engine-python
> E: Unable to locate package google-cloud-sdk-app-engine-python
> E: Unable to locate package google-cloud-sdk-datastore-emulator
> E: Unable to locate package google-cloud-sdk-app-engine-go

I think some additional repositories need to be put before using this command.

**Comment by kp625544** [comment]
Can add this as a reference in document: 

> https://cloud.google.com/sdk/docs/downloads-apt-get

**Comment by frikky** [comment]
As we don't run Appengine anymore, this line shouldn't be needed. Fixed in latest commit, and also added information for running the database and shuffle-orborus locally.
