### ISSUE TITLE
[Bug] Undo button reverting to the initial state.

### ISSUE THREAD

**Issue by DavidtheGoliath** [frikky/Shuffle#601]
**Is your feature request related to a problem? Please describe.**
After setting up a node with all the settings perfectly, I happened to accidentally delete it. I hit the undo button hoping to be returned to the previous settings I had made, but it only brings back the deleted node minus the settings.

**Describe the solution you'd like**
Would it be possible to have, the settings i.e (Actions previously selected, API key entered, set URL etc.) available at the click of the undo button?  

**Describe alternatives you've considered**
None at the moment

**Comment by frikky** [comment]
What you're describing is intended activity, and this is a bug.

**Comment by frikky** [comment]
Fixed from 0.9.42
