### ISSUE TITLE
[BUG] Clear execution action does not work

### ISSUE THREAD

**Issue by azgaviperr** [frikky/Shuffle#603]
The new addition in nightly to clear all execution doesn't work.
No execution got aborted but possible by python script of the troubleshoot. 

On Backend:

![image](https://user-images.githubusercontent.com/7451354/144876942-c57d3b16-57b1-4353-89f6-60d54444c27f.png)

**Comment by frikky** [comment]
Wondering if this is that it doesn't work, or if it's intended according to the status of the app. Maybe the "ERROR" thing should be debug. Gotta investigate!

Will have to run it overnight and verify :)

**Comment by frikky** [comment]
Should be properly fixed from 0.9.43! Runs aborts AND reruns of workflows that have failed
