### ISSUE TITLE
[Bug] I get an error when searching for an app

### ISSUE THREAD

**Issue by DavidtheGoliath** [frikky/Shuffle#604]
**Describe the bug**
I get an error when I search for any app in the top search field and select an option that jumps at me. I am using shuffle cloud 

**To Reproduce**
See video

https://user-images.githubusercontent.com/31187099/145347732-3d759630-ceea-4e2f-b5f8-ea65d935adf5.mp4

**Expected behavior**
The selected app to load up for use.

**Comment by frikky** [comment]
Fixed in cloud version related to 0.9.40.
