### ISSUE TITLE
[BUG] Clicking on the nodes the editing window doesn't pop up. 

### ISSUE THREAD

**Issue by DavidtheGoliath** [frikky/Shuffle#609]
**Describe the bug**
When I click on a node in  order to bring up the editing window that usually pops up on the right hand side of the platform. Nothing happens it sometimes just drags the node, mind you its on a single click.

**To Reproduce**
1. Open your cloud instance 
2. Try clicking on a node in the workspace
3. Check the response

...

**Expected behavior**
The editing window to pop up and allow me access to the actions among other functions.

**Screenshots**
See video below.

https://user-images.githubusercontent.com/31187099/145948936-023b5a98-a6da-4dd9-a18d-ca3c67ac7419.mp4

**Comment by frikky** [comment]
Verified and rolled back to a previous working version. Thanks for notifying us!

I think this happened just due to update of packages on the frontend. Weird.

**Comment by frikky** [comment]
Properly fixed!
