### ISSUE TITLE
When creating a workflow and double clicking on an app, under the environment drop down, options for both Shuffle and Cloud are visible.

### ISSUE THREAD

**Issue by m1nk-code** [frikky/Shuffle#610]
**Describe the bug**
When creating a workflow and double clicking on an app, under the environment drop down, options for both Shuffle and Cloud are visible.

**To Reproduce**

Browser: Chrome

1. Create a new workflow
2. Drag and drop a Test app
3. Double click on it to modify options
4. Select the environment drop down
5. Shuffle and Cloud options are visible.
...

**Expected behavior**
Expected behavior would be to not see two options in the drop down menu. In this case I believe we should only see the Cloud option.

**Screenshots**
![issue1_screenshot](https://user-images.githubusercontent.com/58112539/146047562-47c94d83-8a9a-41b9-acaa-175fb3012323.png)

** Debug logs **
Run the following commands and paste them
```
docker logs shuffle-backend
docker ps -a
```

**Comment by frikky** [comment]
Fixed!
