### ISSUE TITLE
When using the Zoho App, the result area doesn't give useful output

### ISSUE THREAD

**Issue by m1nk-code** [frikky/Shuffle#614]
**Describe the bug**
When using the Zoho App and attempting to execute anything, the results area does not output any useful information to the user.

**To Reproduce**
1. Search for the Zoho Service Desk App and navigate to it
2. Select any of the actions and click the play button to execute it
3. Notice the results do not output any useful information
...

**Expected behavior**
After selecting an action and executing it, the expectation would be to see more useful information in the results area. 

**Screenshots**

![image](https://user-images.githubusercontent.com/58112539/146283231-60675082-e97a-4919-b6fa-9d065162fb35.png)

**Comment by frikky** [comment]
Fixed the app explorer in general! Just need to add more docs and such, but at least it now has a lot more information when an action fails
