### ISSUE TITLE
[FR] A way to delete authentications if you are no longer using them

### ISSUE THREAD

**Issue by DavidtheGoliath** [frikky/Shuffle#616]
**Is your feature request related to a problem? Please describe.**
It would be nice to get a way to delete authentication credentials you no longer have a need for.

**Describe the solution you'd like**
Get a delete button for deprecated credentials.

**Describe alternatives you've considered**
Maybe get a delete button to clear up credentials you no longer require

**Screenshots of where and how**

![16 12 2021_16 37 43_REC](https://user-images.githubusercontent.com/31187099/146382608-c93d4070-eac7-47d6-a376-6354ae182369.png)

Maybe a small delete button at the side of the credentials

**Comment by frikky** [comment]
This is available in the /admin panel, under authentications. Not sure if we should add it to the UI itself, as it would just clutter it. What do you think?

**Comment by DavidtheGoliath** [comment]
That works, isn't it a bit far though? Navigating all the way to the admin panel, how would a new user know where to get it? Unless our documentation is on top of this.

**Comment by frikky** [comment]
> That works, isn't it a bit far though? Navigating all the way to the admin panel, how would a new user know where to get it? Unless our documentation is on top of this.

I think it's fine, as deleting typically is a bad and permanent action that probably breaks something, and you wouldn't want just anyone to be able to do it.
