### ISSUE TITLE
[FR]/[BUG] Enabling file upload when creating a new task setting applies but later reverts back.

### ISSUE THREAD

**Issue by DavidtheGoliath** [frikky/Shuffle#619]
**Is your feature request related to a problem? Please describe.**
I wasn't sure if this is a bug or a FR. When creating a new action you get an option with 2 buttons New query or Enable file upload. I earlier selected enable file upload. This setting applies for a while then vanishes and the set action doesn't come with the enable file option

**Describe the solution you'd like**
Could we get this setting to stick the way you set it initially?

**Screenshots of where and how**

![17 12 2021_18 15 18_REC](https://user-images.githubusercontent.com/31187099/146566149-42c36591-6df5-4833-bac2-a79974db6e67.png)

**Comment by frikky** [comment]
This was a frontend bug, where it literally didn't load it IF a body existed for the request at the same time! Fixed in 0.9.41.
