### ISSUE TITLE
Logstash App for data manipulation & enrichment and as a one-stop-shop

### ISSUE THREAD

**Issue by getkub** [frikky/Shuffle#621]
**Is your feature request related to a problem? Please describe.**
Logstash is highly flexible and contains almost any kind of INPUT type & data manipulation and is highly versatile.
Including such an app can make shuffler quite powerful by accepting any type of input, producing any actions etc.

**Describe alternatives you've considered**
Logstash app can act as an app of last resort as it has more than 60+ input types, filters to data manipulate to any level and have outputs/integrations to more than dozen industry standard methods

So the request is to include Logstash app/container into Shuffler platform

**Comment by getkub** [comment]
thanks for taking it up

**Comment by frikky** [comment]
Closing as it's tracked in the other repository
