### ISSUE TITLE
Inconsistent size of front-end app icons

### ISSUE THREAD

**Issue by 219liangyi** [frikky/Shuffle#624]
![image](https://user-images.githubusercontent.com/19781251/146711738-8bd335ac-3b79-4f5c-b8c2-2ad59bed5e83.png)
Some are very big and some are very small. You see, they are very small

**Comment by frikky** [comment]
Hey there! This is purposefully done. Short version:
Circle = Start node.
Octogon = Triggers.
Big Square = Apps that are not directly Shuffle related
Small apps = Utility functions from Shuffle

**Comment by 219liangyi** [comment]
No, I want to express two squares. Why is one so big and the other so small? Shouldn't they be the same size?
