### ISSUE TITLE
Options not available when making app from app creator

### ISSUE THREAD

**Issue by 219liangyi** [frikky/Shuffle#626]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/19781251/146715929-62cdecd3-da24-4a27-a9fa-7f72a5a589eb.png">

Some parameters, eg: type, have only a few options. I hope this is optional when I create workflows. Just select it. It feels troublesome every time I enter it. I also need to find out what values this type has, because its values are fixed, just a few

**Comment by frikky** [comment]
> <img alt="image" width="370" src="https://user-images.githubusercontent.com/19781251/146715929-62cdecd3-da24-4a27-a9fa-7f72a5a589eb.png">
> 
> Some parameters, eg: type, have only a few options. I hope this is optional when I create workflows. Just select it. It feels troublesome every time I enter it. I also need to find out what values this type has, because its values are fixed, just a few

This is up to how the apps are made, and depends on the creator of it whether they add it or not. Over time, we'll make sure to add it most places possible.

E.g. in this case, what app are you using?

**Comment by 219liangyi** [comment]
我通过open api 创建的应用程序

**Comment by 219liangyi** [comment]
The application I created through the create from scratch front end

**Comment by 219liangyi** [comment]
This approach is not supported

**Comment by frikky** [comment]
> This approach is not supported

Thanks! I'm migrating this to a feature request, as it should indeed be supported there. Thanks! :fire:
