### ISSUE TITLE
[Bug] Subflow starting node selection disapear on reloading workflow

### ISSUE THREAD

**Issue by azgaviperr** [frikky/Shuffle#629]
Starting node selection disapear for Subflow nodes disapear when reloading a workflow or going into it. 

Issue is if we save the workflow, the value stays empty and the worflow executions stale. 

![image](https://user-images.githubusercontent.com/7451354/146791551-89204a07-a071-4407-8344-56c0398c0d46.png)

**Comment by frikky** [comment]
Fixed! Will be a part of 0.9.43.
