### ISSUE TITLE
[FR] Shuffle tools Send text and Email trial

### ISSUE THREAD

**Issue by DavidtheGoliath** [frikky/Shuffle#633]
**Is your feature request related to a problem? Please describe.**
Maybe get a trial for people interested in using the Shuffle tools Send SMS and Send Email actions.

**Describe the solution you'd like**
Get maybe 10 or so tries for testing these actions.

**Comment by frikky** [comment]
Done! Added 50 emails and 10 sms monthly for new registers to the platform. May go over and fix all previous orgs as well.
