### ISSUE TITLE
Add comment bug

### ISSUE THREAD

**Issue by 219liangyi** [frikky/Shuffle#637]
After I click the add comment button, a box pops up. I don't know what it is for, and there is no document, mainly because I can't delete it

![image](https://user-images.githubusercontent.com/19781251/147386245-9641b95d-9e74-44cd-9c6c-1c78ea429edc.png)

**Comment by frikky** [comment]
Hey and thanks! What browser are you on? It looks kind of bugged.

For reference, this is how it's supposed to look: 
![image](https://user-images.githubusercontent.com/5719530/147771555-3cec107c-e033-497c-8761-a669dfcbf484.png)

It is in general just a comment field where you can type in some information and place it somewhere. Here's our open issue about documenting the use of it: https://github.com/Shuffle/Shuffle-docs/issues/54
