### ISSUE TITLE
Found 89 vulnerabilities (82 low, 2 moderate, 5 high) in npm while building images

### ISSUE THREAD

**Issue by OzzyKampha** [frikky/Shuffle#64]
**Describe the bug**
When building the images. i found that npm is using modules that are old and therefor have vulnerabilities.  you should upgrade these module so there are no more vulnerabilities.

found 89 vulnerabilities (82 low, 2 moderate, 5 high)

**To Reproduce**
1. Run docker-compose build

**Expected behavior**
building mages for use in shuffle

**Comment by frikky** [comment]
Thanks! I guess this is NPM telling you. I'll have to change some frontend things to make the audit pass, not just upgrade the packages.

**Comment by OzzyKampha** [comment]
Yes it is NPM that is telling it while building the frontend.

**Comment by frikky** [comment]
Fixed in commit https://github.com/frikky/Shuffle/commit/96b5998ce025269adda61e1b48a52eef8d81c8ee. Regenerated new package-lock.json as well.
