### ISSUE TITLE
Documentation in browser is buggy - Navigation showing in a strange way

### ISSUE THREAD

**Issue by m1nk-code** [frikky/Shuffle#647]
**Describe the bug**
When navigating to shuffler.io/docs the page visually looks broken.

**To Reproduce**
1. Go to shuffler.io/docs
2. View navigation displaced 
...

**Expected behavior**
Expecting to see everything lined up appropriately in the browser. 

**Screenshots**
![image](https://user-images.githubusercontent.com/58112539/147782354-cdcdbb6a-75e1-4bf0-b785-3c66c60444bd.png)

**Comment by frikky** [comment]
Hopefully fixed. Will push new update tomorrow so we can see :)
