### ISSUE TITLE
Bug in App Creator Header Field Parsor

### ISSUE THREAD

**Issue by m1nk-code** [frikky/Shuffle#648]
**Describe the bug**
When attempting to use app creator to GET tasks in Zoho Desk, there's a bug in trying to do so.

Curl:

curl -X GET "https://desk.zoho.com/api/v1/tasks?departmentId=634000000000006000&include=teams,tickets,contacts,assignee" -H "orgId:767300000" -H "Authorization:Zoho-oauthtoken 1000.eacbd4a123458d674000a000631586000.f5184c9db584a858e1f5d4bab347ef74"

![image](https://user-images.githubusercontent.com/58112539/147787976-33615156-01c2-4569-95b8-e6510bb66de3.png)

**Comment by frikky** [comment]
Fixed in #168
