### ISSUE TITLE
Casting values from previous nodes bug

### ISSUE THREAD

**Issue by benjamino21** [frikky/Shuffle#65]
Hi again, thanks for helping me with SSL verification. Now, I've created some endpoints for QRadar app to get info using Offenses like domain info or source/destination. My problem is that sending variables from previous node is giving me problem. Example: if I look for info from a domain with its id as a parameter (GET /api/config/domain_management/domains/{domain_id} action) it gives me the correct info but if I try to pass the id from a previous node it gives me the following error: "Failed to transform user path parameter "domain_id" with a content type of "TEXT_PLAIN. Could not convert from to Integer"" 
Is there a way to cast it as integer? For example, selecting the type of the parameter in App creator.

Update: I've tried to download the Open API definition generated by Shuffle and change the type specified in schema but when I import it, it changes again to string.

**Comment by frikky** [comment]
Hey again @benjamino21,

this was a design decision I made early on, as casting from string is trivial in most cases (there's a lot of other reasons for this choice as well). One thing I _haven't_ done so far is to make auto-casting for anything other than JSON, but I guess this is as good a time as  any.

I didn't really get your specific problem though. Wouldn't domain_id be a string in every case anyway, as it's a part of the URL? Even with a string, it should just be a part of the URL, e.g. /api/config/domain_management/domains/123. I totally get it if it would be a part of the body or something instead.

I'll get on this asap :+1:

**Comment by benjamino21** [comment]
I'll show you in images. First image is the app I've created
![imagen](https://user-images.githubusercontent.com/50662824/84873689-e953a980-b083-11ea-916a-a807f63bdd71.png)
The main query is to get offenses by id. From that query, I get the domain_id for the query /api/config/domain_management/domains/{domain_id}.
My problem is the following: if i perform the action /api/config/domain_management/domains/{domain_id} introducing the domain_id manually as parameter, I get the expected result:
![imagen](https://user-images.githubusercontent.com/50662824/84874571-15235f00-b085-11ea-8198-e7cb72bff6a4.png)
![imagen](https://user-images.githubusercontent.com/50662824/84874652-34ba8780-b085-11ea-8eaa-00256ca2be7e.png)
But if i pass it from a previous node, it gives me the following error:
![imagen](https://user-images.githubusercontent.com/50662824/84874843-78ad8c80-b085-11ea-88d4-e33ac3f7b8ec.png)
![imagen](https://user-images.githubusercontent.com/50662824/84874955-9f6bc300-b085-11ea-9b30-4e9a5faa92a9.png)
![imagen](https://user-images.githubusercontent.com/50662824/84875017-b3afc000-b085-11ea-9ae7-d1a01ec35d60.png)
I hope you understand it better 👍 
Maybe it's a problem of parsing parameters from previous nodes or maybe it's QRadar problem.
Thank you for all the work done!

**Comment by frikky** [comment]
Because auto-casting might become a mess and the user loses control, I've decided to add programming functionality for cases like this instead. It will start with basic functionality like int(DATA) and lower(DATA) or upper(DATA) which should give way to easily fix issues like this.

I'll update here when it's in there :+1:

**Comment by frikky** [comment]
Hey again @benjamino21, here's a list of the functions I added.

![image](https://user-images.githubusercontent.com/5719530/85005022-8849d580-b158-11ea-87d1-d184d5b19ad6.png)

The two most important ones for you would be "number" and "parse", as they respectively are integer and list casting options. Parse: parse(list, slice). List = an array. Slice = python slice: https://stackoverflow.com/questions/509211/understanding-slice-notation

* Get value "1" as integer: number(1) 
* Get first value in a list: parse(["hello1", "hello2"],0)
* Get last item in list: parse(["hello1", "hello2"], -1)

Hope it helps this and possibly other situations. PS: it might be error prone as I didn't test every single angle.
Get the new app sdk then rebuild your app :+1:

```
docker pull frikky/shuffle:app_sdk
```
