### ISSUE TITLE
[Bug] Problem with code editor

### ISSUE THREAD

**Issue by DavidtheGoliath** [frikky/Shuffle#652]
**Describe the bug**
There is a problem with the code editor, when I click on the expand window activation it works in some fields and doesn't in others. Using cloud version,issue exists both on Chrome and Firefox.

**To Reproduce**
See video

https://user-images.githubusercontent.com/31187099/147907866-2b453278-1033-4d41-a42d-1fb778e63b1b.mp4

**Comment by frikky** [comment]
Thanks!

This has been fixed in the version we're deploying later this week.
