### ISSUE TITLE
How to stop this task globally

### ISSUE THREAD

**Issue by 219liangyi** [frikky/Shuffle#660]
hi:
   Recently, I encountered a scene that can't be solved.
I have a scheduled task cycle. When the data in it meets certain conditions, I need to terminate this scheduled task. How to terminate this scheduled task globally?
   thank you

**Comment by 219liangyi** [comment]
The next scheduled task will be executed normally. It's not a complete termination of the choreography

**Comment by frikky** [comment]
So if I understand you correctly: 

You want to cancel a schedule IF it meets a certain condition? Try using the Shuffle API for stopped a schedule directly: https://shuffler.io/docs/API#stop_a_workflow_schedule

Do you want it to restart as well?

**Comment by 219liangyi** [comment]
hi: I've solved her. It's a problem in my mind. It is still somewhat different from the conventional development idea
