### ISSUE TITLE
[BUG] Dict with key as string int

### ISSUE THREAD

**Issue by D4rkw0lv3s** [frikky/Shuffle#661]
**Describe the bug**
When migrating my app to launch version my function map key values stopped working correctly when using a string number as key.

**To Reproduce**
1. Execute the function with a dict that uses string number as key
{
  "2": 1
}
2. Error:
src property must be a valid json object

**Expected behavior**
Accept it and return 1 when the input is 3 or return the no value message or if no message return the input value

**Screenshots**
![image](https://user-images.githubusercontent.com/21691729/148554552-3b9308cd-03f8-4646-b729-4cdd522cf003.png)

![image](https://user-images.githubusercontent.com/21691729/148554404-1f1cd592-fce9-491a-b771-04c28f05c417.png)
If the key is not a number but something like the code below it return the correct value "blah":
{
  "blah": 1
}
![image](https://user-images.githubusercontent.com/21691729/148554732-abf530ce-e822-404e-94a6-d30aeba1b0df.png)

** Debug logs (NOT APPLICABLE FOR CLOUD)**
Run the following commands and paste them
```
docker logs shuffle-backend
docker ps -a
```

**Comment by frikky** [comment]
ooh, I just realized: This is a frontend bug that's already fixed. The problem is that it was trying to interpret numbers as JSON. 

Will push a nightly build later tonight that has it handled. PS: This is JUST a frontend bug, meaning the value is still correct and can be used as a normal variable.
