### ISSUE TITLE
[Bug] Name changing a node doesn't change needs a refresh to change node name

### ISSUE THREAD

**Issue by DavidtheGoliath** [frikky/Shuffle#668]
**Describe the bug**
Title tells it all

**To Reproduce**
1. Run installation '...'
2. Create workflow '...'
3. Click on '....'
...

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

** Debug logs (NOT APPLICABLE FOR CLOUD)**
Run the following commands and paste them
```
docker logs shuffle-backend
docker ps -a
```

**Comment by frikky** [comment]
Should have been fixed.
