### ISSUE TITLE
[Bug] Results too large to handle

### ISSUE THREAD

**Issue by DavidtheGoliath** [frikky/Shuffle#669]
**Describe the bug**
Getting results of a running execution with the error as stated in the title, "Results too large to handle."

**To Reproduce**
1. Run installation '...'
2. Create workflow '...'
3. Click on '....'
...

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

** Debug logs (NOT APPLICABLE FOR CLOUD)**
Run the following commands and paste them
```
docker logs shuffle-backend
docker ps -a
```

**Comment by frikky** [comment]
Should have been fixed.
