### ISSUE TITLE
Support multibyte character in post request body parameters.

### ISSUE THREAD

**Issue by oginoPmP** [frikky/Shuffle#67]
Hi, I want to use the multibyte character in the post request body parameters.
When post a JSON contains multibyte characters, that outputs the following error message.
```
Exception: 'latin-1' codec can't encode characters in position 21-29: Body ('ＭＵＬＴＩＢＹＴＥ') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```
Is there a way to avoid this error?

**Comment by frikky** [comment]
Havent dealt with this before so i'll have to read up. For reproduction, where do you get that reply exactly and with what data?

Thanks!

**Comment by oginoPmP** [comment]
Used a custom app (attached text file) and the following JSON.
```
{
    "title": "ＭＵＬＴＩＢＹＴＥ",
    "description": "This case has been created by my custom script"
}
```
My team would use Japanese characters in many cases, so I need to multibyte characters support.
[thehive_cases.txt](https://github.com/frikky/Shuffle/files/4799960/thehive_cases.txt)

**Comment by frikky** [comment]
No worries, I'd love to help with this. Maybe I can practice my Japanese at the same time :100:

**Comment by frikky** [comment]
Run an [update](https://shuffler.io/docs/configuration#updating_shuffle) and then rebuild the app (save again).

Didn't test too much, so tell me how it goes :)

**Comment by oginoPmP** [comment]
Thanks, my app is working correctly!
