### ISSUE TITLE
'Result too large to handle' Error for Small Result Set

### ISSUE THREAD

**Issue by ropetin** [frikky/Shuffle#673]
**Describe the bug**
When using the 'Filter List' feature of the Shuffle Tools app, I get the dreaded '[ERROR] Result too large to handle (https://github.com/frikky/shuffle/issues/171)' error trying to filter on a JSON blob result from an Elasticsearch query that produces a response ~350 KB in size.   Ignoring that 0.5 MB max size as noted in 171 is an annoyingly low setting, given the kind of data Shuffle is designed to work with, this is below that size and is still generating the error.

Additionally, is there any workaround or clear plan to remove the limitation documented in 171?  It is making it increasingly hard to recommend Shuffle given this significant limit on data set size.

**To Reproduce**
1. Run an Elasticsearch query to return a blob size ~350 KB
2. Pass the results to 'Filter List'
3. Confirm the error is generated
...

**Expected behavior**
The filter is correctly applied

**Screenshots**
N/A

** Debug logs (NOT APPLICABLE FOR CLOUD)**
Run the following commands and paste them
```
2022/01/11 17:33:56 [INFO] Setting value of Filter_for_IPs (e0149cec-8649-4136-9c7b-53405f368e01) in workflow 9       29b3393-dd62-4b2b-beeb-0569e4b73e89 to SUCCESS
2022/01/11 17:33:56 [ERROR] Result length is too long! Need to reduce result size
```

**Comment by frikky** [comment]
Hey! 

You're absolutely right, which is why there is literally no limit at all in the later versions. Did you see this in your frontend as well, or just in the logs?

it is still a soft limit in our cloud version, which is what this got mixed up with.

**Comment by frikky** [comment]
> Well I feel like an ass now :/ Thanks for setting me straight. I did an upgrade and as far as I can tell everything is working like a champ!

Hahah, no worries at all! It was initially discovered for the exact same reason you saw it here, and we won't be able to make the right updates without these reports, so we're always happy to get reports of possible issues.
