### ISSUE TITLE
Local repo - Githib for Visual Studio - project files deleted

### ISSUE THREAD

**Issue by jimmyhaggard** [frikky/Shuffle#68]
**Describe the bug**
I use Windows 10 and Visual Studio 2019. 

I decided to use the GitHub extension with Visual Studio 2019 to set up a local repository.  I went through the process via the gui.  I pushed all files from a Visual Studio WPF project folder to the local repository.   The files consisted of forms and c# code. 

When I checked the local repository activity history, only 1/3 of the project files were listed.  I went to my main project location, and 2/3 of the files were gone.  The only files in my main project folder were those that were listed in the github history.   The local repository was on a different disk drive than the main project files.  I checked the recycle bin, and the missing files were not there.  I searched all local disk drives and the missing files were no where to be found. 

While using the github extension for visual studio, at no time did I encounter any messages or prompts about disposing, deleting or removing any files.  All I did was push the project files to a local repository.  

As a result of using the Github extension for Visual Studio, 2/3 of my project files appear to have been permanently deleted (not sent to the recycle bin, but permanently erased).  

The only good news is that I saved the entire project to a ZIP files and archived it about week ago.  I was able to extract my project files, and it only set me back a week.  However, it was a very productive week. 

My conclusion is that there is a seriously bad bug in the github extension for Visual Studio. 

Unless you can tell me where I can find my project files, I do not want to hear a word from anyone.

BTW, I will NOT attempt to recreate the issue, it already wiped out 2/3 of my projects files once and I have no intention of experiencing that again.   What I will do is NEVER USE GITHUB again.

**Comment by frikky** [comment]
Hey @jimmyhaggard! This doesn't sound like a problem with Shuffle (this project), but I'll still give you a hand if you want. Reach out to me at frikky@shuffler.io and we can set something up.

**Comment by jimmyhaggard** [comment]
My apologies. Out of frustration I posted the issue in the wrong place.

**Comment by frikky** [comment]
No harm done! Hope you have a nice weekend and figure it out :champagne:
