### ISSUE TITLE
[FR/BUG] Passing lists - Improvement

### ISSUE THREAD

**Issue by D4rkw0lv3s** [frikky/Shuffle#683]
## **Problem**
Nowadays when you try to call a list of dics with sublists of dicts , it doesn't work well in one call. 

#### Input:
```
[
    {
        "key1": [
            {
                "sub_key1": "value1",
                "sub_key2": "value2"
            } 
        ],
        "key2": [
            {
                "sub_key1": "value1",
                "sub_key2": "value2"
            } 
        ]
    },
    {
        "key1": [
            {
                "sub_key1": "value1",
                "sub_key2": "value2"
            } 
        ],
        "key2": [
            {
                "sub_key1": "value1",
                "sub_key2": "value2"
            } 
        ]
    }
]
```

#### Node Call:
```
exec.#.key1
```

#### Node Output:
```
[
    [
        {
            "sub_key1":"value1",
            "sub_key2":"value2"
        }
    ],
    [
        {
            "sub_key1":"value1",
            "sub_key2":"value2"
        }
    ]
]
```

#### Expected Output:
```
[
    {
        "sub_key1":"value1",
        "sub_key2":"value2"
    },
    {
        "sub_key1":"value1",
        "sub_key2":"value2"
    }
]
```

## **Screenshot Example:**
![image](https://user-images.githubusercontent.com/21691729/150192244-e733d653-8cb5-466c-b5cb-8e51753a643e.png)

## **Custom app function code:**
```
def handle_loop(self, list_value, key_value):

        list_value = (
            json.loads(list_value) if isinstance(list_value, str) else list_value
        )

        final_list = []
        if key_value:
            for item in list_value:
                final_list += item[key_value]
        else:
            for item in list_value:
                final_list += item

        return final_list
```

## **Solution:**

Shuffle could handle this type of lists by outputing in one unique list of all the values of that key. Like Tools does when you pass the input as "list_value" and **key1** as "key_value", what is translated to **exec.#.key1**.

**Comment by frikky** [comment]
You're right, thanks!

Gonna test it later and see whether it's a quickfix or not. It could be due to a bug in the magic parsing, as it's key feature is to make lists of things that aren't :thinking:

**Comment by D4rkw0lv3s** [comment]
@frikky Yup I confirm it is because of magic parsing. Maybe adding an option to disable by default magic parsing?

**Comment by frikky** [comment]
Disabled by default and now working as expected :)
