### ISSUE TITLE
[Bug] The code editor is a bit buggy

### ISSUE THREAD

**Issue by DavidtheGoliath** [frikky/Shuffle#697]
**Describe the bug**
The code editor doesn't allow me to edit it in any single way once I click on enlarging the code editor it pops up and when I click to edit the values within it it just vanishes. See video below. 

**To Reproduce**

https://user-images.githubusercontent.com/31187099/151653790-154c5663-ed74-4dc5-bda5-d87ccf22ace7.mp4

**Comment by frikky** [comment]
Hola!

This was a temporary fix to something else that made it not work, and was fixed in testing yesterday.

Thanks!

**Comment by DavidtheGoliath** [comment]
Okay glad to hear that. Thanks.

**Comment by frikky** [comment]
Has been fixed!
