### ISSUE TITLE
Possible SDK issue with replacement of \

### ISSUE THREAD

**Issue by OpenSecureCo** [frikky/Shuffle#707]
Possible SDK issue with replacement of \.

Hey Team

Facing an issue where I am looking to do a regex replace using liquid. The regex replace functionality is working correctly, however, when getting the result, the "\" are missing. Unfortunately, the subsequent node that I use the regex replace result to make the api call needs the "\" to function correctly. Below are screenshots detailing the issue.

Liquid regex replace:
{{'$get_pipeline_id.source' | regex_replace:'0 match either\nrule','0 match either\nrule "Route Wazuh Events to customer $customer"\nrule'}}

What the request needs to be :
![image](https://user-images.githubusercontent.com/74164997/153535924-c572edee-468a-40ed-aab4-36e1ad7a300c.png)

What it is:

![image](https://user-images.githubusercontent.com/74164997/153535955-e1dbb369-9154-4269-a49d-a313de457ba4.png)

Thanks for the help!

**Comment by frikky** [comment]
Looks like an SDK issue which we can fix with ast eval of the JSON data instead of manual manipulation. Should be fixable easily :)

**Comment by frikky** [comment]
I believe this is fixed with the latest SDK updates which try to parse and send data as actual JSON instead of a string. Haven't seen a similar issue in the past few months
