### ISSUE TITLE
Add usecase mapping for workflows for better discovery

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#709]
Came about from a question with creators: how can they make and discover usecases more easily?

This should be the very early version of that.

**Comment by frikky** [comment]
Basic dashboard playground to see what's possible and how to discover things 
![image](https://user-images.githubusercontent.com/5719530/154826264-2e65a89d-6031-43a9-b78a-98f80b38aabc.png)

**Comment by frikky** [comment]
Basic workflow mapping to workflows. NOTE: Uses the same colors, and allows both filtering and setting of data.

![image](https://user-images.githubusercontent.com/5719530/154826272-01bf6e07-b3f6-4a75-9fc2-57d9dceb8ed3.png)

![image](https://user-images.githubusercontent.com/5719530/154826288-543ee300-370e-422f-acfa-962ac3a8adba.png)

**Comment by frikky** [comment]
This all came about from some drawings and mindmaps (which includes exports):

![image](https://user-images.githubusercontent.com/5719530/154826325-e9f4bc64-3617-43ee-8e69-2c5811881f83.png)

Code for managing the import to shuffle can be found here: https://github.com/frikky/Shuffle/tree/launch/functions/usecases

**Comment by frikky** [comment]
Where the mapping came from:

![20220220_034642.jpg](https://user-images.githubusercontent.com/5719530/154826380-2d9977ad-d5c6-488c-a21d-4ca0ed7b7159.jpg)

![20220220_034631.jpg](https://user-images.githubusercontent.com/5719530/154826385-38e874d2-223a-4dd0-b222-5b01693a7f49.jpg)

**Comment by frikky** [comment]
This has been started and has a new process for [putting workflows in production](https://github.com/Shuffle/Shuffle-docs/blob/master/handbook/engineering/workflow_release_process.md)

Thanks @DavidtheGoliath :)

**Comment by DavidtheGoliath** [comment]
No worries @frikky.
