### ISSUE TITLE
Existence based Shuffle Variable Highlighting in Code Editor

### ISSUE THREAD

**Issue by gohil-jay** [frikky/Shuffle#724]
**Is your feature request related to a problem? Please describe.**
With hundreds of lines of code, it is infeasible to keep track of shuffle variables in the code editor.

**Describe the solution you'd like**
Highlight the shuffle variables (different colors for whether they are right or not) in the code editor.

**Describe alternatives you've considered**
N/A.

**Additional context**
Variable highlighting in major code editors.

**Screenshots of where and how**
![Snap](https://user-images.githubusercontent.com/59703162/156772789-5832ba3c-8eab-4b3b-9421-4bdbae740064.png)

**Comment by frikky** [comment]
Fixed some time back :+1: 

Still missing subvariables and more visuals
