### ISSUE TITLE
[Bug] integer in query are interpreted as string

### ISSUE THREAD

**Issue by azgaviperr** [frikky/Shuffle#806]
Insight IDR app with value on integer query doesn't work anymore.
Example in list investigation if size or index have data, the message returnerd is a server error. Only string query can get specified.

![image](https://user-images.githubusercontent.com/7451354/162786847-c896daca-ff1d-4dc4-90a4-5894506bcee2.png)

Same things use to work two weeks ago

**Comment by frikky** [comment]
> Insight IDR app with value on integer query doesn't work anymore. Example in list investigation if size or index have data, the message returnerd is a server error. Only string query can get specified.
> 
> ![image](https://user-images.githubusercontent.com/7451354/162786847-c896daca-ff1d-4dc4-90a4-5894506bcee2.png)
> 
> Same things use to work two weeks ago

Same as the other query bug. It was JSON parsing happening on pretty much any query
